Packages/net.fushizen.modular-avatar/Editor/BoneProxyHook.cs
Packages/net.fushizen.modular-avatar/Editor/HookBase.cs
Packages/net.fushizen.modular-avatar/Editor/HookBase.cs.meta
Packages/net.fushizen.modular-avatar/Editor/LastResortTagComponentCleaner.cs
Packages/net.fushizen.modular-avatar/Editor/MergeAnimatorHook.cs
Packages/net.fushizen.modular-avatar/Editor/MergeArmatureHook.cs
Packages/net.fushizen.modular-avatar/Editor/MeshRetargeter.cs
Packages/net.fushizen.modular-avatar/Editor/PathMappings.cs

https://feedback.vrchat.com/sdk-bug-reports/p/exceptions-thrown-from-onpreprocessavatar-hooks-do-not-abort-the-build

Workaround vrc bug - exceptions don't halt build

---

Packages/net.fushizen.modular-avatar/Editor/AnimatorMerger.cs
Packages/net.fushizen.modular-avatar/Editor/MergeAnimatorProcessor.cs
Packages/net.fushizen.modular-avatar/Runtime/ModularAvatarMergeAnimator.cs

Various improvements for merge animator

---

Packages/net.fushizen.modular-avatar/Editor/BoneProxyProcessor.cs
Packages/net.fushizen.modular-avatar/Editor/Inspector.meta
Packages/net.fushizen.modular-avatar/Editor/Inspector/AvatarObjectReferenceDrawer.cs
Packages/net.fushizen.modular-avatar/Editor/Inspector/AvatarObjectReferenceDrawer.cs.meta
Packages/net.fushizen.modular-avatar/Editor/Inspector/BoneProxyEditor.cs
Packages/net.fushizen.modular-avatar/Editor/Inspector/BoneProxyEditor.cs.meta
Packages/net.fushizen.modular-avatar/Editor/MergeArmatureHook.cs
Packages/net.fushizen.modular-avatar/Editor/Util.cs
Packages/net.fushizen.modular-avatar/Runtime/AvatarObjectReference.cs
Packages/net.fushizen.modular-avatar/Runtime/AvatarObjectReference.cs.meta
Packages/net.fushizen.modular-avatar/Runtime/ModularAvatarBoneProxy.cs
Packages/net.fushizen.modular-avatar/Runtime/ModularAvatarMergeArmature.cs
Packages/net.fushizen.modular-avatar/Runtime/RuntimeUtil.cs

Note: This breaks prefab compatibility.
Fixes #38

Support drag-and-drop of prefab instances between avatars

---

Packages/net.fushizen.modular-avatar/Editor/Inspector/AvatarObjectReferenceDrawer.cs
Packages/net.fushizen.modular-avatar/Runtime/AvatarObjectReference.cs

AvatarObjectReference defaults to a null referent

---

Packages/net.fushizen.modular-avatar/Editor/AvatarProcessor.cs
Packages/net.fushizen.modular-avatar/Editor/Inspector/AvMenuTreeView.cs
Packages/net.fushizen.modular-avatar/Editor/Inspector/AvMenuTreeView.cs.meta
Packages/net.fushizen.modular-avatar/Editor/Inspector/AvatarParametersEditor.cs
Packages/net.fushizen.modular-avatar/Editor/Inspector/AvatarParametersEditor.cs.meta
Packages/net.fushizen.modular-avatar/Editor/Inspector/MenuInstallerEditor.cs
Packages/net.fushizen.modular-avatar/Editor/Inspector/MenuInstallerEditor.cs.meta
Packages/net.fushizen.modular-avatar/Editor/MenuInstallHook.cs
Packages/net.fushizen.modular-avatar/Editor/MenuInstallHook.cs.meta
Packages/net.fushizen.modular-avatar/Editor/ParameterPolicy.cs
Packages/net.fushizen.modular-avatar/Editor/ParameterPolicy.cs.meta
Packages/net.fushizen.modular-avatar/Editor/RenameParametersHook.cs
Packages/net.fushizen.modular-avatar/Editor/RenameParametersHook.cs.meta
Packages/net.fushizen.modular-avatar/Runtime/ModularAvatarMenuInstaller.cs
Packages/net.fushizen.modular-avatar/Runtime/ModularAvatarMenuInstaller.cs.meta
Packages/net.fushizen.modular-avatar/Runtime/ModularAvatarParameters.cs
Packages/net.fushizen.modular-avatar/Runtime/ModularAvatarParameters.cs.meta
Packages/net.fushizen.modular-avatar/Samples/Clap/ClapMenu.asset
Packages/net.fushizen.modular-avatar/Samples/Clap/ClapMenu.asset.meta
Packages/net.fushizen.modular-avatar/Samples/Clap/ClapSample.prefab
Packages/net.fushizen.modular-avatar/Samples/Clap/clap_controller.controller

Add support for merging parameters and menus

---

Packages/net.fushizen.modular-avatar/Editor/Inspector/MenuInstallerEditor.cs
Packages/net.fushizen.modular-avatar/Editor/Localization/en.json
Packages/net.fushizen.modular-avatar/Editor/Localization/ja.json
Packages/net.fushizen.modular-avatar/Editor/MenuInstallHook.cs
Packages/net.fushizen.modular-avatar/Editor/RenameParametersHook.cs
Packages/net.fushizen.modular-avatar/Runtime/ModularAvatarMenuInstaller.cs
docs/docs/reference/menu-installer.md

Menu Installer: Default to installing at top level

---

Packages/nadena.dev.modular-avatar/Editor/EasySetupOutfit.cs

https://github.com/bdunderscore/modular-avatar/issues/101

armatureの子を1と仮定せずに全探査するように修正

---

Packages/nadena.dev.modular-avatar/Editor/MeshRetargeter.cs

https://github.com/bdunderscore/modular-avatar/issues/112

素体とスケールの違う衣装を着せる時、バウンディングボックスがサイズ差の分変わってしまうバグの修正

---

Packages/nadena.dev.modular-avatar/Editor/AnimatorMerger.cs
Packages/nadena.dev.modular-avatar/Editor/RenameParametersHook.cs

Fix animator cloning creating duplicate MonoScript objects

---

Packages/nadena.dev.modular-avatar/Editor/EasySetupOutfit.cs

[ui] prevent Setup Outfit from running on an avatar root

---

Packages/nadena.dev.modular-avatar/Editor/EasySetupOutfit.cs

Enable (but no-op) setup outfit when outfit is already setup

---

Packages/nadena.dev.modular-avatar/Editor/MeshRetargeter.cs

Fix NRE caused by missing root bone

---

Packages/nadena.dev.modular-avatar/Editor/MergeArmatureHook.cs

This fixes issues where outfits which duplicate the PB components from the
base avatar can result in PB motion breaking after merge.

Prune duplicate PBs on merge armature

---

Packages/nadena.dev.modular-avatar/Runtime/Activator.cs

* Activator tries to mark scene dirty in play mode (fixes #164)
* Activator creates multiple hidden objects which build up over time

fix: multiple bugs in Activator

---

Packages/nadena.dev.modular-avatar/Editor/Util.cs

fix: proxy animations broken on legacy VRCSDK

---

Packages/nadena.dev.modular-avatar/Editor/AnimationDatabase.cs

fix: ArgumentNullException when blend tree clips are missing/none

---

Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling.meta
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/AC1.controller
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/AC1.controller.meta
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/Base.controller
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/Base.controller.meta
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/BaseController.prefab
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/BaseController.prefab.meta
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/MergedController.prefab
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/MergedController.prefab.meta
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/SyncedLayerHandling.cs
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/SyncedLayerHandling.cs.meta
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/m1.anim
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/m1.anim.meta
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/m2.anim
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/m2.anim.meta
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/m3.anim
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/m3.anim.meta
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/m4.anim
Assets/_ModularAvatar/EditModeTests/SyncedLayerHandling/m4.anim.meta
Assets/_ModularAvatar/EditModeTests/TestBase.cs
Packages/nadena.dev.modular-avatar/Editor/AnimatorMerger.cs

fix: synced layer motion overrides not preserved over MA processing

---

Packages/nadena.dev.modular-avatar/Editor/Util.cs

It seems that sometimes static initializers are created before the icon annotations are updated. This change checks for this case, and defers the icon-disabling until after the necessary annotation records are created.

fix: sometimes the MA icons aren't disabled properly

---

Packages/nadena.dev.modular-avatar/Editor/Inspector/AvatarParametersEditor.cs

This doesn't fully close #217, but it's an improvement. Fully fixing it will require reworking the UI fully (or getting unity to fix their terrible code :/)

fix: improve parameter inspector perf when using lots of parameters

---

Packages/nadena.dev.modular-avatar/Editor/HeuristicBoneMapper.cs

feat: add chest=bust mapping for the heuristic bone mapper

---

Packages/nadena.dev.modular-avatar/Editor/AvatarProcessor.cs
Packages/nadena.dev.modular-avatar/Editor/OptimizationPasses.meta
Packages/nadena.dev.modular-avatar/Editor/OptimizationPasses/GCGameObjectsPass.cs
Packages/nadena.dev.modular-avatar/Editor/OptimizationPasses/GCGameObjectsPass.cs.meta

Add an optimization pass to delete GameObjects that don't affect the final avatar

feat: destroy unused GameObjects

---

Assets/_ModularAvatar/EditModeTests/AnimateAddedBones/AnimateAddedBones.cs
Assets/_ModularAvatar/EditModeTests/DirectBlendTreeParameters/DBTP.anim
Assets/_ModularAvatar/EditModeTests/DirectBlendTreeParameters/DBTP.anim.meta
Assets/_ModularAvatar/EditModeTests/DirectBlendTreeParameters/DBTP.controller
Assets/_ModularAvatar/EditModeTests/DirectBlendTreeParameters/DBTP.controller.meta
Assets/_ModularAvatar/EditModeTests/DirectBlendTreeParameters/DirectBlendTreeParameters.cs
Assets/_ModularAvatar/EditModeTests/DirectBlendTreeParameters/DirectBlendTreeParameters.cs.meta
Assets/_ModularAvatar/EditModeTests/DirectBlendTreeParameters/DirectBlendTreeParameters.prefab
Assets/_ModularAvatar/EditModeTests/DirectBlendTreeParameters/DirectBlendTreeParameters.prefab.meta
Assets/_ModularAvatar/EditModeTests/SimpleArmatureToggle/SimpleArmatureToggle.cs
Assets/_ModularAvatar/EditModeTests/TestBase.cs
Assets/_ModularAvatar/EditModeTests/TransformMappingThroughSwitchedObject/TransformMappingThroughSwitchedObject.cs
Packages/nadena.dev.modular-avatar/Editor/RenameParametersHook.cs

fix: direct blend parameters not being remapped

---

Assets/_ModularAvatar/EditModeTests/RenameParametersTests/InstalledMenu 1.asset
Assets/_ModularAvatar/EditModeTests/RenameParametersTests/InstalledMenu 1.asset.meta
Assets/_ModularAvatar/EditModeTests/RenameParametersTests/InstalledMenu.asset
Assets/_ModularAvatar/EditModeTests/RenameParametersTests/InstalledMenu.asset.meta
Assets/_ModularAvatar/EditModeTests/RenameParametersTests/RenameInstalledMenu.prefab
Assets/_ModularAvatar/EditModeTests/RenameParametersTests/RenameInstalledMenu.prefab.meta
Assets/_ModularAvatar/EditModeTests/RenameParametersTests/RenameParametersTests.cs
Assets/_ModularAvatar/EditModeTests/RenameParametersTests/m1.asset
Assets/_ModularAvatar/EditModeTests/RenameParametersTests/m1.asset.meta
Assets/_ModularAvatar/EditModeTests/RenameParametersTests/m2.asset
Assets/_ModularAvatar/EditModeTests/RenameParametersTests/m2.asset.meta
Assets/_ModularAvatar/EditModeTests/TestBase.cs
Packages/nadena.dev.modular-avatar/Editor/Menu/VirtualMenu.cs

Thanks to suzuryg for finding the cause of the bug and suggesting an initial fix.
Reported-By: 33linn
Fixes: #305

fix: internal parameters not renamed on installed VRCExpressionMenu submenus

---

Assets/_ModularAvatar/EditModeTests/MergeArmatureTests.meta
Assets/_ModularAvatar/EditModeTests/MergeArmatureTests/ColliderMergeTest.prefab
Assets/_ModularAvatar/EditModeTests/MergeArmatureTests/ColliderMergeTest.prefab.meta
Assets/_ModularAvatar/EditModeTests/MergeArmatureTests/MergeArmatureTests.cs
Assets/_ModularAvatar/EditModeTests/MergeArmatureTests/MergeArmatureTests.cs.meta
Packages/nadena.dev.modular-avatar/Editor/MeshRetargeter.cs

fix: Don't strip objects which contain unrecognized components

---

Packages/nadena.dev.modular-avatar/Editor/OptimizationPasses/GCGameObjectsPass.cs

https://twitter.com/Appletea_VRC/status/1666046954558853125 の修正です

fix: ArgumentException with components with missing script

---

Packages/nadena.dev.modular-avatar/Editor/ParameterPolicy.cs

fix: add VelocityMagnitude as builtin parameter

---

Packages/nadena.dev.modular-avatar/Editor/HeuristicBoneMapper.cs

fix: add some heuristic bone mappings

---

.github/workflows/build-release.yml

`pCYSl5EDgo/create-unitypackage`が壊れたので結構前に作った私の作ったcreate-unitypackageに置き換えました

build: use anatawa12's create-unitypackage instead of broken one

---

Packages/nadena.dev.modular-avatar/Editor/AnimationDatabase.cs
Packages/nadena.dev.modular-avatar/Editor/AnimatorMerger.cs
Packages/nadena.dev.modular-avatar/Editor/AvatarProcessor.cs
Packages/nadena.dev.modular-avatar/Editor/BuildContext.cs
Packages/nadena.dev.modular-avatar/Editor/MergeAnimatorProcessor.cs
Packages/nadena.dev.modular-avatar/Editor/Util.cs
Packages/nadena.dev.modular-avatar/Runtime/MAAssetBundle.cs
Packages/nadena.dev.modular-avatar/Runtime/MAAssetBundle.cs.meta

- chore: use binary serialization for generated assets
- chore: automatically save assets referenced at the end of processing

chore: improvements to asset handling

---

Packages/nadena.dev.modular-avatar/Editor/AvatarProcessor.cs

fix: adjust processing order for Mesh Settings

---

Packages/nadena.dev.modular-avatar/Editor/ApplyOnPlay.cs

enter playmode settings が有効だとarmedSourceがリセットされずAwakeで実行されないので修正しました

fix: MA is not performed in Awake if enter playmode settings is enabled

---

Packages/nadena.dev.modular-avatar/Editor/Inspector/ReplaceObjectEditor.cs

fix: replace object UI doesn't allow the target to be set

---

docs/docs/reference/menu-install-target.md
docs/i18n/ja/docusaurus-plugin-content-docs/current/reference/menu-install-target.md

docs: fix broken link (#383)

---

Assets/_ModularAvatar/EditModeTests/ComponentSettingsTest.cs
Assets/_ModularAvatar/EditModeTests/ComponentSettingsTest.cs.meta

test: add test for icon of components

---

docs/docs/reference/visible-head-accessory.md

docs: First Person Visible -> Visible Head Accessory

---

Packages/nadena.dev.modular-avatar/Editor/Inspector/Menu/MenuInstallerEditor.cs

fix: menu installer GUI selection window is broken

---

Packages/nadena.dev.modular-avatar/Editor/HeuristicBoneMapper.cs

feat: disregard digits in heuristic bone mapper

---

Packages/nadena.dev.modular-avatar/Editor/EasySetupOutfit.cs
Packages/nadena.dev.modular-avatar/Editor/Localization/Localization.cs
Packages/nadena.dev.modular-avatar/Editor/Localization/en.json
Packages/nadena.dev.modular-avatar/Editor/Localization/ja.json

Show a descriptive error when setup outfit fails (fixes #415).
Use HeuristicBoneMapper to fuzzy-match hips (fixes #414)

ui: improve setup outfit usability

---

Packages/nadena.dev.modular-avatar/Editor/AvatarProcessor.cs

workaround avatar matching problem

---

Assets/_ModularAvatar/EditModeTests/AvatarObjectReferenceTest.cs
Assets/_ModularAvatar/EditModeTests/AvatarObjectReferenceTest.cs.meta
Assets/_ModularAvatar/EditModeTests/GameObjectGC/GameObjectGC.cs
Packages/nadena.dev.modular-avatar/Editor/OptimizationPasses/GCGameObjectsPass.cs
Packages/nadena.dev.modular-avatar/Runtime/AvatarObjectReference.cs

fix: workaround issues with double-Armature hack

---

Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockController.cs
Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/TransformState.cs
Packages/nadena.dev.modular-avatar/Runtime/MAMoveIndependently.cs

Fixes #449
Asset Bundle作るテストはやしたほうがいいのかな(Runtime Build CEを探すため)

fix: compile error on runtime build

---

Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/BidirectionalArmatureLock.cs
Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/OnewayArmatureLock.cs

fix: NPEs resulting from bones being deleted under armature lock

---

Assets/_ModularAvatar/EditModeTests/BuildAssetBundle.cs
Assets/_ModularAvatar/EditModeTests/BuildAssetBundle.cs.meta

生やした方がよさそうですね…
_Originally posted by @bdunderscore in https://github.com/bdunderscore/modular-avatar/issues/450#issuecomment-1733766924_

test: add test for runtime build

---

Packages/nadena.dev.modular-avatar/Editor/Inspector/MergeArmatureEditor.cs

fix: error if MergeArmature is not under an avatar

---

Packages/nadena.dev.modular-avatar/Editor/Localization/ja.json

日本語訳での、位置追従モードの説明が少しわかりにくいと感じたので修正しました。

位置追従モードの説明の日本語訳を修正

---

Runtime/MAMoveIndependently.cs
Runtime/Menu/ModularAvatarMenuGroup.cs
Runtime/Menu/ModularAvatarMenuInstaller.cs
Runtime/ModularAvatarBlendshapeSync.cs
Runtime/ModularAvatarBoneProxy.cs
Runtime/ModularAvatarMenuInstallTarget.cs
Runtime/ModularAvatarMenuItem.cs
Runtime/ModularAvatarMergeAnimator.cs
Runtime/ModularAvatarMergeArmature.cs
Runtime/ModularAvatarMeshSettings.cs
Runtime/ModularAvatarPBBlocker.cs
Runtime/ModularAvatarParameters.cs
Runtime/ModularAvatarReplaceObject.cs
Runtime/ModularAvatarVisibleHeadAccessory.cs
Runtime/ModularAvatarWorldFixedObject.cs
UnitTests~/ComponentSettingsTest.cs

Now you can open website with clicking `?` button on the inspector

add HelpURL Attribute

---

Editor/WorldFixedObjectProcessor.cs
UnitTests~/WorldFixedObjectTest/WorldFixedObjectTest.cs

fix: name collision issues with World Fixed Object

---

Editor/Inspector/Menu/MenuInstallerEditor.cs

fix: select menu creates menu install targets in random order

---

docs~/i18n/ja/docusaurus-plugin-content-docs/current/reference/world-fixed-object.md

docs(ja/world-fixed-object): fix typo

---

docs~/docs/intro.md
docs~/i18n/ja/docusaurus-plugin-content-docs/current/intro.md

docs: remove mention of unitypackage installation

---

Editor/BoneProxyProcessor.cs
UnitTests~/BoneProxyTest.cs

fix: name collisions with Bone Proxies break animation mappings

---

Editor/EasySetupOutfit.cs
Editor/Inspector/MergeArmatureEditor.cs
Editor/MergeArmatureHook.cs
Editor/OptimizationPasses/GCGameObjectsPass.cs
Editor/VisibleHeadAccessoryProcessor.cs
Runtime/ModularAvatarBoneProxy.cs
Runtime/ModularAvatarMergeArmature.cs
UnitTests~/BlendshapeSyncTests/BlendshapeSyncIntegrationTest.prefab
UnitTests~/MergeArmatureTests/ColliderMergeTest.prefab

fix: Erros in Unity 2022 because GetBoneTransform errors for generic avatars

---

Editor/CreateBlendTree.cs
Editor/CreateBlendTree.cs.meta

Not sure where to put it, so into the root editor folder it goes.

Added BlendTree to right click create asset menu.

---

Editor/ReplaceObjectPass.cs

Fixes #547. See my comment there for context.

fix: Replace Object dropping children (bdunderscore#547)

---

Runtime/ArmatureAwase/OnewayArmatureLock.cs

fix: zero scale on outfit destroys transform data

---

.github/ProjectRoot/vpm-manifest-2019.json
.github/ProjectRoot/vpm-manifest-2022.json
Editor/AnimatorMerger.cs
Editor/MergeAnimatorProcessor.cs
UnitTests~/Animation/LayerPruningTest.cs
UnitTests~/Animation/LayerPruningTest.cs.meta
UnitTests~/Animation/LayerPruningTest.meta
UnitTests~/Animation/LayerPruningTest.prefab
UnitTests~/Animation/LayerPruningTest.prefab.meta
UnitTests~/Animation/LayerPruningTest/A1.anim
UnitTests~/Animation/LayerPruningTest/A1.anim.meta
UnitTests~/Animation/LayerPruningTest/A2.anim
UnitTests~/Animation/LayerPruningTest/A2.anim.meta
UnitTests~/Animation/LayerPruningTest/A3.anim
UnitTests~/Animation/LayerPruningTest/A3.anim.meta
UnitTests~/Animation/LayerPruningTest/AC1.controller
UnitTests~/Animation/LayerPruningTest/AC1.controller.meta
UnitTests~/Animation/LayerPruningTest/AC2.controller
UnitTests~/Animation/LayerPruningTest/AC2.controller.meta
UnitTests~/Animation/LayerPruningTest/AC3.controller
UnitTests~/Animation/LayerPruningTest/AC3.controller.meta
UnitTests~/BlendshapeSyncTests/BlendshapeSyncIntegrationTest.prefab
UnitTests~/SyncedLayerHandling/AC1.controller
UnitTests~/TestBase.cs
package.json

feat: prune empty layers

---

Editor/EasySetupOutfit.cs

fix: enable wordwrap for ESO error dialog

---

Editor/Inspector/ScaleAdjusterInspector.cs
Editor/Inspector/ScaleAdjusterTool.cs
Editor/Inspector/ScaleAdjusterTool.cs.meta

fix: ScaleAdjuster not usable when gizmos are not enabled

---

Editor/Menu/MenuExtractor.cs

fix: improve null checks in CloneControl

---

.github/ProjectRoot/vpm-manifest-2019.json
.github/ProjectRoot/vpm-manifest-2022.json
Editor/Animation/AnimationDatabase.cs
package.json

fix: issues with blendtree handling in AnimationDatabase

---

Editor/Localization/ja-jp.json

fix: incorrect placeholder in jp translation

---

.github/ProjectRoot/vpm-manifest-2019.json
.github/ProjectRoot/vpm-manifest-2022.json
Editor/Inspector/Parameters/DefaultValueField.cs
Editor/Inspector/Parameters/DefaultValueField.cs.meta
Editor/Inspector/Parameters/ParameterConfigDrawer.cs
Editor/Inspector/Parameters/ParameterConfigDrawer.uxml
Editor/Inspector/Parameters/Parameters.uss
Editor/Localization/en-us.json
Editor/RenameParametersHook.cs
Runtime/ModularAvatarParameters.cs
UnitTests~/BlendshapeSyncTests/BlendshapeSyncIntegrationTest.prefab
UnitTests~/RenameParametersTests/EmptyMenu.asset
UnitTests~/RenameParametersTests/EmptyMenu.asset.meta
UnitTests~/RenameParametersTests/ParameterConflictTestParams.asset
UnitTests~/RenameParametersTests/ParameterConflictTestParams.asset.meta
UnitTests~/RenameParametersTests/ParameterConflicts.prefab
UnitTests~/RenameParametersTests/ParameterConflicts.prefab.meta
UnitTests~/RenameParametersTests/ParameterResolution.prefab
UnitTests~/RenameParametersTests/ParameterResolution.prefab.meta
UnitTests~/RenameParametersTests/RenameParametersTests.cs
package.json

- feat(params): track whether a default value was explicitly set
- feat(params): improve default value resolution and error handling
Closes: #557

feat(params): Allow for MA Parameters to _not_ specify a default value

---

Editor/Localization/en-us.json
Editor/Localization/ja-jp.json
Editor/WorldFixedObjectProcessor.cs

fix: world fixed object breaks android builds

---

Editor/ParameterPolicy.cs

Fix: add missing sdk parameters

---

Editor/Inspector/Parameters/ParameterConfigDrawer.cs
Editor/Inspector/Parameters/ParameterConfigDrawer.uxml
Editor/Localization/en-us.json
Editor/Localization/ja-jp.json

fix: missing translations on "automatic" rename-to field

---

Editor/Animation/AnimatorCombiner.cs
Editor/Inspector/MergeArmatureEditor.cs
Editor/Inspector/MergeBlendTreeEditor.cs
Editor/MergeArmatureHook.cs
Editor/MergeBlendTreePass.cs
Editor/OptimizationPasses/PruneParametersPass.cs
Editor/PluginDefinition/PluginDefinition.cs
Editor/nadena.dev.modular-avatar.core.editor.asmdef
Runtime/ModularAvatarMergeBlendTree.cs
Runtime/ModularAvatarScaleAdjuster.cs
UnitTests~/Animation/LayerPruningTest.cs
UnitTests~/Animation/MergeBlendTreeTest.cs
UnitTests~/Animation/MergeOrderTest.cs
UnitTests~/EasySetupOutfit/PreferFirstHipsMatch.cs
UnitTests~/MergeArmatureTests/MergeArmatureTests.cs

Fixed some compile errors I've found when using Modular Avatar in non-VRChat project.

chore: Fix non-VRChat support

---

Editor/Animation/AnimatorCombiner.cs
Editor/MergeAnimatorProcessor.cs
UnitTests~/Animation/LayerPruningTest.cs
UnitTests~/Animation/MergeBlendTreeTest.cs
UnitTests~/Animation/MergeOrderTest.cs
UnitTests~/MergeAnimatorTests.meta
UnitTests~/MergeAnimatorTests/TypeAdjustment.meta
UnitTests~/MergeAnimatorTests/TypeAdjustment/ConvertTransitionTypes.cs
UnitTests~/MergeAnimatorTests/TypeAdjustment/ConvertTransitionTypes.cs.meta
UnitTests~/MergeAnimatorTests/TypeAdjustment/ConvertTransitionTypes.prefab
UnitTests~/MergeAnimatorTests/TypeAdjustment/ConvertTransitionTypes.prefab.meta
UnitTests~/MergeAnimatorTests/TypeAdjustment/CrossLayerTypeConsistency.prefab
UnitTests~/MergeAnimatorTests/TypeAdjustment/CrossLayerTypeConsistency.prefab.meta
UnitTests~/MergeAnimatorTests/TypeAdjustment/ac1.controller
UnitTests~/MergeAnimatorTests/TypeAdjustment/ac1.controller.meta
UnitTests~/MergeAnimatorTests/TypeAdjustment/ac2.controller
UnitTests~/MergeAnimatorTests/TypeAdjustment/ac2.controller.meta
UnitTests~/MergeAnimatorTests/TypeAdjustment/ac_empty.controller
UnitTests~/MergeAnimatorTests/TypeAdjustment/ac_empty.controller.meta
UnitTests~/MergeAnimatorTests/TypeAdjustment/cltc_0.controller
UnitTests~/MergeAnimatorTests/TypeAdjustment/cltc_0.controller.meta
UnitTests~/MergeAnimatorTests/TypeAdjustment/cltc_1.controller
UnitTests~/MergeAnimatorTests/TypeAdjustment/cltc_1.controller.meta
UnitTests~/TestBase.cs

feat: convert animator parameters to float when types are inconsistent

---

Editor/Animation/AnimationUtil.cs
Editor/Animation/AnimatorCombiner.cs
UnitTests~/MergeAnimatorTests/TypeAdjustment/ConvertTransitionTypes.cs
UnitTests~/MergeAnimatorTests/TypeAdjustment/ac1.controller

- fix: float conversion breaks substatemachine entry transitions
- fix: unnecessary type conversions
Closes: #669

fix: float conversion breaks sub-state-machine entry transitions, including FaceEmo

---

Editor/AvatarProcessor.cs
Editor/Localization/Localization.cs
Runtime/ArmatureAwase/ArmatureLockController.cs
Runtime/ArmatureAwase/BidirectionalArmatureLock.cs
Runtime/ArmatureAwase/IArmatureLock.cs
Runtime/ArmatureAwase/OnewayArmatureLock.cs
Runtime/ArmatureAwase/UpdateLoopController.cs
Runtime/ModularAvatarMergeArmature.cs
Runtime/UI.meta
Runtime/UI/UnityMenuItems.cs
Runtime/UI/UnityMenuItems.cs.meta

- opti(armature-lock): parallelize burst jobs for armature lock processing
- feat: continue armature tracking when the MAMA GameObject is disabled
- feat: add global toggle for armature locking

feat: improvements to armature tracking

---

Editor/ScaleAdjusterPass.cs

fix: build fails when entries in the bones array are null

---

Editor/BuildContext.cs
Editor/MergeAnimatorProcessor.cs
UnitTests~/MergeAnimatorTests/AOC_Base.controller
UnitTests~/MergeAnimatorTests/AOC_Base.controller.meta
UnitTests~/MergeAnimatorTests/AOC_Override.overrideController
UnitTests~/MergeAnimatorTests/AOC_Override.overrideController.meta
UnitTests~/MergeAnimatorTests/Anim1.anim
UnitTests~/MergeAnimatorTests/Anim1.anim.meta
UnitTests~/MergeAnimatorTests/Anim2.anim
UnitTests~/MergeAnimatorTests/Anim2.anim.meta
UnitTests~/MergeAnimatorTests/MergeSingleTests.cs
UnitTests~/MergeAnimatorTests/MergeSingleTests.cs.meta

fix: handle AnimatorOverrideController (and null animator controllers) in Merge Animator

---

docs~/package.json
docs~/src/css/custom.css
docs~/yarn.lock

- chore(docs): update dependencies
- fix(docs): images are squished when too large for their container

chore(docs): docs dependency update and minor fixes

---

Editor/Inspector/BoneProxyEditor.cs

fix: change attachment mode causes non-undoable transform movement

---

Editor/RenameParametersHook.cs
UnitTests~/RenameParametersTests/RenameParametersTests.cs

fix: parameter order is shuffled

---

Editor/HeuristicBoneMapper.cs
Editor/MergeArmatureHook.cs
Runtime/ModularAvatarMergeArmature.cs

fix: bones whose name exactly matches prefix+suffix incorrectly match their parent (?)

---

Runtime/ArmatureAwase/AllocationMap.cs
Runtime/ArmatureAwase/AllocationMap.cs.meta
Runtime/ArmatureAwase/ArmatureLockController.cs
Runtime/ArmatureAwase/ArmatureLockJob.cs
Runtime/ArmatureAwase/ArmatureLockJobAccessor.cs
Runtime/ArmatureAwase/ArmatureLockOperator.cs
Runtime/ArmatureAwase/BidirectionalArmatureLock.cs
Runtime/ArmatureAwase/NativeMemoryManager.cs
Runtime/ArmatureAwase/NativeMemoryManager.cs.meta
Runtime/ArmatureAwase/OnewayArmatureLock.cs
Runtime/ArmatureAwase/TransformState.cs
UnitTests~/ArmatureAwase.meta
UnitTests~/ArmatureAwase/AllocationMapTest.cs
UnitTests~/ArmatureAwase/AllocationMapTest.cs.meta
UnitTests~/ArmatureAwase/NativeMemoryManagerTest.cs
UnitTests~/ArmatureAwase/NativeMemoryManagerTest.cs.meta

... by avoiding reinitializing everything whenever any target bone moves.

opti: fix perf regressions in new armature lock system

---

Runtime/ScaleAdjuster/ProxyManager.cs

Thanks to @TCL987 for the suggestion!

chore: use forceRenderingOff for ProxyManager

---

Runtime/ScaleAdjuster/ModularAvatarScaleAdjuster.cs

fix: parent scale ignored in Scale Adjuster

---

Runtime/ArmatureAwase/ArmatureLockOperator.cs

fix: double free message from armature lock

---

Editor/EasySetupOutfit.cs

fix: nullref from Setup Outfit on non-humanoid rigs

---

Editor/VisibleHeadAccessoryProcessor.cs
UnitTests~/VisibleHeadAccessoryTest.meta
UnitTests~/VisibleHeadAccessoryTest/VHA_anim.anim
UnitTests~/VisibleHeadAccessoryTest/VHA_anim.anim.meta
UnitTests~/VisibleHeadAccessoryTest/VHA_controller.controller
UnitTests~/VisibleHeadAccessoryTest/VHA_controller.controller.meta
UnitTests~/VisibleHeadAccessoryTest/VHA_shapell.prefab
UnitTests~/VisibleHeadAccessoryTest/VHA_shapell.prefab.meta
UnitTests~/VisibleHeadAccessoryTest/VisibleHeadAccessoryTest.cs
UnitTests~/VisibleHeadAccessoryTest/VisibleHeadAccessoryTest.cs.meta

fix: Visible Head Accessory breaks transform animations

---

Editor/Animation/AnimatorCombiner.cs
UnitTests~/MergeAnimatorTests/TypeAdjustment/ConvertTransitionTypes.cs
UnitTests~/MergeAnimatorTests/TypeAdjustment/ac1.controller

fix: type corrections not applied to substatemachine exit transitions

---

Editor/Inspector/Menu/MenuInstallerEditor.cs
Editor/ParamsUsage/ParamsUsageEditor.cs

- fix: NullReferenceError while deleting a GameObject with parameter usage UI open
- fix: NullRefException from editor when moving a Menu Installer outside of an avatar
Closes: #788

fix: NullRefExceptions from inspectors

---

Editor/ParamsUsage/nadena.dev.modular-avatar.param-introspection.asmdef

fix: don't use GUID references in asmdef

---

Runtime/ScaleAdjuster/ModularAvatarScaleAdjuster.cs
Runtime/ScaleAdjuster/ProxyManager.cs

- fix: Scale Adjusters outside an avatar throw exceptions
- fix: improve scale adjuster performance

fix: Scale Adjusters outside an avatar throw exceptions

---

Editor/BuildContext.cs

fix: self-referencing menus result in stack overflow

---

Editor/ParamsUsage/ParamsUsagePrefs.cs
Editor/ParamsUsage/ParamsUsagePrefs.cs.meta
Editor/ParamsUsage/ParamsUsageUI.cs
Runtime/UI/UnityMenuItems.cs

feat: add menu option to disable "modular avatar information" display

---

Editor/EasySetupOutfit.cs

fix: NRE in EasySetupOutfit

---

Editor/Animation/AnimatorCombiner.cs
UnitTests~/MergeAnimatorTests/SyncedLayerOverrideInSubStatemachine.meta
UnitTests~/MergeAnimatorTests/SyncedLayerOverrideInSubStatemachine/SyncedLayerOverrideInSubStateMachine.cs
UnitTests~/MergeAnimatorTests/SyncedLayerOverrideInSubStatemachine/SyncedLayerOverrideInSubStateMachine.cs.meta
UnitTests~/MergeAnimatorTests/SyncedLayerOverrideInSubStatemachine/anim.anim
UnitTests~/MergeAnimatorTests/SyncedLayerOverrideInSubStatemachine/anim.anim.meta
UnitTests~/MergeAnimatorTests/SyncedLayerOverrideInSubStatemachine/syncedlayer.controller
UnitTests~/MergeAnimatorTests/SyncedLayerOverrideInSubStatemachine/syncedlayer.controller.meta

repro case provided by @anatawa12

fix: synced layers with substatemachines are broken

---

Editor/ScaleAdjuster/ScaleAdjusterPreview.cs
Editor/ShapeChanger/ShapeChangerPreview.cs

- chore: implement refresh for ScaleAdjusterPreview
- chore: implement refresh in ShapeChangerPreview

chore: implement preview refresh

---

Editor/ActiveAnimationRetargeter.cs
Editor/Animation/AnimationServicesContext.cs
Editor/Animation/DeepClone.cs
Editor/Animation/EditorCurveBindingComparer.cs
Editor/Animation/EditorCurveBindingComparer.cs.meta
Editor/Animation/PathMappings.cs
Editor/Animation/ReadableProperty.cs
Editor/Animation/ReadableProperty.cs.meta
Editor/PluginDefinition/PluginDefinition.cs
Editor/ShapeChanger/PropertyOverlayPass.cs
Editor/ShapeChanger/PropertyOverlayPass.cs.meta
Editor/ShapeChanger/ShapeChangerPass.cs.meta
UnitTests~/ActiveAnimationRetargeterTests/ActiveAnimationRetargeterTests.cs
UnitTests~/ShapeChanger/InitialStates/SCDefaultAnimation.cs

- **refactor: generalize the shape changer implementation a bit**
- **feat: shape changer can respond to multiple parent objects being animated**

feat: shape changer can respond to multiple parent objects being animated

---

Editor/ShapeChanger/ShapeChangerPreview.cs

fix: missing observe in ShapeChangerPreview

---

Editor/Animation/AnimationDatabase.cs
Editor/Animation/AnimationServicesContext.cs
Editor/Animation/GameObjectDisableDelayPass.cs
Editor/Animation/GameObjectDisableDelayPass.cs.meta
Editor/Animation/ReadableProperty.cs
Editor/PluginDefinition/PluginDefinition.cs

feat: delay GameObjects turning OFF by one frame, when they control ShapeChangers

---

.github/ProjectRoot/vpm-manifest-2022.json
Editor/Inspector/AvatarObjectReferenceDrawer.cs
Editor/Inspector/Menu/MenuItemGUI.cs
Editor/Inspector/ObjectToggle/ToggledObjectEditor.cs
Editor/ParamsUsage/MAParametersIntrospection.cs
Editor/PluginDefinition/PluginDefinition.cs
Editor/ReactiveObjects/ControlCondition.cs
Editor/ReactiveObjects/ControlCondition.cs.meta
Editor/ReactiveObjects/MenuItemPreviewCondition.cs
Editor/ReactiveObjects/MenuItemPreviewCondition.cs.meta
Editor/ReactiveObjects/ObjectTogglePreview.cs
Editor/ReactiveObjects/ParameterAssignerPass.cs
Editor/ReactiveObjects/ParameterAssignerPass.cs.meta
Editor/ReactiveObjects/PropertyOverlayPass.cs
Editor/ReactiveObjects/ShapeChangerPreview.cs
Editor/RenameParametersHook.cs
Runtime/AvatarObjectReference.cs
Runtime/ModularAvatarMenuItem.cs
Runtime/ModularAvatarObjectToggle.cs
Runtime/ModularAvatarShapeChanger.cs
Runtime/ReactiveComponent.cs
Runtime/ReactiveComponent.cs.meta
UnitTests~/BlendshapeSyncTests/BlendshapeSyncIntegrationTest.prefab
package.json

- **refactor: generalize support for arbitrary parameters as conditions**
- **feat: automatically assign Menu Item parameters**
- **feat: ReactiveComponents respond to MenuItems**
- **feat: AvatarObjectReference tracks both paths and direct object references**

Connect reactive components to MenuItems

---

Editor/Animation/PathMappings.cs

fix: not all clip settings are copied properly

---

.github/ProjectRoot/vpm-manifest-2022.json
Editor/VisibleHeadAccessoryProcessor.cs
UnitTests~/VisibleHeadAccessoryTest/VisibleHeadAccessoryTest.cs
package.json

feat: use VRCHeadChop for VisibleHeadAccessory

---

Editor/Animation/DeepClone.cs

fix: actually fix cursed interaction with unity timeline

---

Editor/Inspector/Parameters/DefaultValueField.cs
Editor/Inspector/Parameters/ParameterConfigDrawer.cs
Editor/Inspector/Parameters/ParameterConfigDrawer.uxml
Editor/Inspector/Parameters/Parameters.uss

ui: redesign MA parameters UI

---

Editor/MergeAnimatorProcessor.cs

fix: missing layers in avatar descriptor can result in KeyNotFoundException

---

Editor/ReactiveObjects/ParameterAssignerPass.cs
Editor/ReactiveObjects/PropertyOverlayPass.cs

- **fix: initial state does not set proxy variables for toggled objects**
- **fix: incorrect constant analysis in property overlay pass**
- **fix: reactive objects respond to parent submenu active state inappropriately**
- **fix: property overlay pass does not register itself in animation database**

fix: multiple bugs discovered during dogfooding

---

Editor/ReactiveObjects/ParameterAssignerPass.cs

fix: only create autoparams when a reactive component is present

---

docs~/src/css/custom.css

docs: add drop shadow to logo in light mode

---

Editor/Inspector/MaterialSetter/MaterialSetter.uxml
Editor/Inspector/MaterialSetter/MaterialSetterStyles.uss
Editor/Inspector/MaterialSetter/MaterialSwitchObjectEditor.cs
Editor/Inspector/MaterialSetter/MaterialSwitchObjectEditor.uxml
Editor/Inspector/Menu/MenuPreviewGUI.cs
Editor/Inspector/Menu/ToggleCreatorShortcut.cs
Editor/Inspector/Menu/ToggleCreatorShortcut.cs.meta
Editor/Inspector/ObjectToggle/ObjectSwitcher.uxml
Editor/Inspector/ShapeChanger/ShapeChanger.uxml
Editor/Localization/en-US.json
Editor/Localization/ja-JP.json
Runtime/ModularAvatarMenuItem.cs
Runtime/UI/UnityMenuItems.cs

- **ui: adjustments to reactive object UI**
- **ui: toggle creation shortcuts**

ui adjustments; added toggle creation shortcuts

---

Editor/ParamsUsage/MAParametersIntrospection.cs
Editor/ReactiveObjects/ParameterAssignerPass.cs
Editor/ReactiveObjects/ShapeChangerPreview.cs

- **fix: shape changer preview does not respect inverted mode**
- **fix: incorrect parameter generation for non-direct-child MAMIs**

additional minor fixes

---

Runtime/ArmatureAwase/AllocationMap.cs
Runtime/ArmatureAwase/ArmatureLockController.cs
Runtime/ArmatureAwase/ArmatureLockJob.cs
Runtime/ArmatureAwase/ArmatureLockOperator.cs
Runtime/ArmatureAwase/NativeMemoryManager.cs
Runtime/ArmatureAwase/OnewayArmatureLock.cs

fix: a bunch of bugs related to invalid jobs in ArmatureAwase

---

Editor/ParamsUsage/MAParametersIntrospection.cs
UnitTests~/RenameParametersTests/RecursiveRenameTest.controller
UnitTests~/RenameParametersTests/RecursiveRenameTest.controller.meta
UnitTests~/RenameParametersTests/RecursiveRenameTest.prefab
UnitTests~/RenameParametersTests/RecursiveRenameTest.prefab.meta
UnitTests~/RenameParametersTests/RenameParametersTests.cs

fix: recursive parameter mappings are not correctly handled

---

Editor/Inspector/Menu/MenuItemGUI.cs

fix: menu item settings are overwritten when selecting multiple menu items

---

Editor/CheckBoneMapping.cs.meta
Editor/Inspector/Menu/MenuItemGUI.cs
UnitTests~/BlendshapeSyncTests/BlendshapeSyncIntegrationTest.prefab

feat: show parameter checkboxes when parameters are defined elsewhere/multiselect is active

---

Runtime/ArmatureAwase/NativeMemoryManager.cs

fix: use-after-free issue in NativeMemoryManager

---

Runtime/MAMoveIndependently.cs

fix: MA Move Independently is not listed in the MA group in Add Components

---

Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs
UnitTests~/ShapeChanger/InitialStates/SCDefaultAnimation.cs
UnitTests~/ShapeChanger/InitialStates/SCDefaultAnimation.prefab

fix: constant reactive objects are incorrectly animated to original scene state

---

Runtime/AvatarTagComponent.cs
Runtime/ReactiveObjects/ModularAvatarMaterialSetter.cs
Runtime/ReactiveObjects/ModularAvatarObjectToggle.cs
Runtime/ReactiveObjects/ModularAvatarShapeChanger.cs

fix: implement ResolveReferences for reactive objects

---

Editor/Inspector/Menu/ParameterField.cs

fix: NRE from Menu Item UI when expression parameters is missing

---

Editor/Inspector/ScaleAdjusterTool.cs

fix: scale adjuster tool rotation is not updated appropriately

---

Editor/Inspector/Menu/MenuItemGUI.cs

fix: showing menu contents of an expression menu throws an NRE

---

Samples/Fingerpen.prefab

fix: spurious "missing" value shown in fingerpen prefab

---

Runtime/ArmatureAwase/OnewayArmatureLock.cs

fix: incorrect parent bone reference in OnewayArmatureLockOperator

---

Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs
Editor/ReactiveObjects/MaterialSetterPreview.cs

Closes #1041 です。
ndmf が MeshRenderer と SkinnedMeshRenderer 以外のプレビューに対応していなさそうだったので、エラーが出ないようにだけしておきました。

fix: support renderers other than SMR

---

Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPrepass.cs

fix: MaterialSetter is not working without ShapeChanger or ObjectToggle

---

Editor/Inspector/MaterialSetter/MaterialSetterStyles.uss
Editor/Inspector/MaterialSetter/MaterialSwitchObjectEditor.cs
Editor/Inspector/MaterialSetter/MaterialSwitchObjectEditor.uxml

feat: improve material setter inspector

---

Editor/HeuristicBoneMapper.cs

improve (but not close): #1044
ねこねこジャージを使用して動作確認済みです

add heuristic bone mapping pattern for LESSER MOKURI

---

Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectAnalyzer.LocateReactions.cs
Runtime/ReactiveObjects/ModularAvatarMaterialSetter.cs
Runtime/ReactiveObjects/ModularAvatarObjectToggle.cs

fix: some issues with reactive objects not triggering pipeline refreshes

---

Editor/Inspector/MaterialSetter/MaterialSwitchObjectEditor.cs
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectAnalyzer.LocateReactions.cs
Editor/ReactiveObjects/MaterialSetterPreview.cs

Closes #1060 です。
インデックスが範囲外の場合は Dropdown を赤文字にして分かるようにしてみました。

Fix material setter index

---

Editor/ReactiveObjects/MaterialSetterPreview.cs

fix: error when deleting Material Setter target

---

Editor/Inspector/MoveIndependently/MoveIndependentlyEditor.cs
Runtime/MAMoveIndependently.cs

feat: serialize Move Independently grouping

---

docs~/docs/unity-2019/index.md
docs~/i18n/ja/docusaurus-plugin-content-docs/current/unity-2019/index.md

docs: update unity 2019 deprecation page

---

docs~/docusaurus.config.js

docs: fix incorrect edit URL

---

Editor/Animation/DeepClone.cs
Editor/RenameParametersHook.cs
UnitTests~/Animation/AnimParameterPathRewrite.meta
UnitTests~/Animation/AnimParameterPathRewrite/AnimParameterPathRewriting.prefab
UnitTests~/Animation/AnimParameterPathRewrite/AnimParameterPathRewriting.prefab.meta
UnitTests~/Animation/AnimParameterPathRewrite/AnimParameterPathRewritingTest.cs
UnitTests~/Animation/AnimParameterPathRewrite/AnimParameterPathRewritingTest.cs.meta
UnitTests~/Animation/AnimParameterPathRewrite/ac1.controller
UnitTests~/Animation/AnimParameterPathRewrite/ac1.controller.meta
UnitTests~/Animation/AnimParameterPathRewrite/ac2.controller
UnitTests~/Animation/AnimParameterPathRewrite/ac2.controller.meta
UnitTests~/Animation/AnimParameterPathRewrite/aoc.overrideController
UnitTests~/Animation/AnimParameterPathRewrite/aoc.overrideController.meta
UnitTests~/Animation/AnimParameterPathRewrite/clip.anim
UnitTests~/Animation/AnimParameterPathRewrite/clip.anim.meta
UnitTests~/Animation/AnimParameterPathRewrite/clip2.anim
UnitTests~/Animation/AnimParameterPathRewrite/clip2.anim.meta

fix: MA Parameters does not update animator parameter curves

---

Editor/Animation/AnimatorCombiner.cs
UnitTests~/Animation/BaseLayerReferenceCorrection.meta
UnitTests~/Animation/BaseLayerReferenceCorrection/BaseLayerReferenceCorrection.prefab
UnitTests~/Animation/BaseLayerReferenceCorrection/BaseLayerReferenceCorrection.prefab.meta
UnitTests~/Animation/BaseLayerReferenceCorrection/BaseLayerReferenceCorrectionTest.cs
UnitTests~/Animation/BaseLayerReferenceCorrection/BaseLayerReferenceCorrectionTest.cs.meta
UnitTests~/Animation/BaseLayerReferenceCorrection/ac.controller
UnitTests~/Animation/BaseLayerReferenceCorrection/ac.controller.meta
UnitTests~/Animation/BaseLayerReferenceCorrection/empty.anim
UnitTests~/Animation/BaseLayerReferenceCorrection/empty.anim.meta

fix: layer cross-references are broken by empty layer pruning in some cases

---

Editor/ScaleAdjuster/ScaleAdjusterPreview.cs
Editor/nadena.dev.modular-avatar.core.editor.asmdef

Fixes a perf issue discovered when investigating #1055 .
Fixes: #1058 (probably)

perf: reimplement ModularAvatarScaleAdjuster

---

Editor/ObjectReferenceFixer.cs
Editor/ObjectReferenceFixer.cs.meta
Runtime/AvatarObjectReference.cs
Runtime/AvatarTagComponent.cs
Runtime/IHaveObjReferences.cs
Runtime/IHaveObjReferences.cs.meta
Runtime/ModularAvatarBlendshapeSync.cs
Runtime/ModularAvatarMergeArmature.cs
Runtime/ModularAvatarMeshSettings.cs
Runtime/ModularAvatarReplaceObject.cs
Runtime/ReactiveObjects/ModularAvatarMaterialSetter.cs
Runtime/ReactiveObjects/ModularAvatarObjectToggle.cs
Runtime/ReactiveObjects/ModularAvatarShapeChanger.cs

feat: update AvatarObjectReference paths when target object is moved in scene

---

Editor/Inspector/Menu/MenuItemGUI.cs

fix: incorrect handling of isDefault toggles for implicit parameters in UI

---

Editor/Inspector/Menu/MenuItemGUI.cs

fix: clearing conflicted MenuItem.isDefault affects unrelated MenuItems

---

Editor/Animation/AnimatorCombiner.cs
Editor/Animation/DeepClone.cs
Editor/Animation/PathMappings.cs
Editor/nadena.dev.modular-avatar.core.editor.asmdef~
UnitTests~/Animation/AvatarMask.meta
UnitTests~/Animation/AvatarMask/AvatarMaskRewriteTest.prefab
UnitTests~/Animation/AvatarMask/AvatarMaskRewriteTest.prefab.meta
UnitTests~/Animation/AvatarMask/AvatarMaskTest.cs
UnitTests~/Animation/AvatarMask/AvatarMaskTest.cs.meta
UnitTests~/Animation/AvatarMask/av-mask-test-ac.controller
UnitTests~/Animation/AvatarMask/av-mask-test-ac.controller.meta
UnitTests~/Animation/AvatarMask/base-fx-ac.controller
UnitTests~/Animation/AvatarMask/base-fx-ac.controller.meta
UnitTests~/Animation/AvatarMask/test-mask.mask
UnitTests~/Animation/AvatarMask/test-mask.mask.meta
UnitTests~/Animation/AvatarMask/test.anim
UnitTests~/Animation/AvatarMask/test.anim.meta

fix: avatar masks are not rewritten when merging animators

---

Editor/Inspector/Menu/MenuItemGUI.cs

fix: Some MenuItemCoreGUI properties do not refresh when rendered in parent menu inspector

---

Editor/Inspector/Menu/MenuItemGUI.cs

We will now force the state of all related MenuItems to match when the
synced/saved checkboxes are updated on the Menu Item UI.
Closes: #1090

ui: improve handling of saved/synced checkboxes on MenuItems with sibling items

---

Editor/ReactiveObjects/Simulator/ROSimulator.cs
Runtime/AvatarObjectReference.cs

Also fix an issue where the clear overrides button doesn't work for menu item overrides.
Closes: #1100

fix: performance issues when RO Simulator is open for too long

---

Editor/RenameParametersHook.cs

Fix nested parameter saved setting

---

Editor/Inspector/Parameters/DefaultValueField.cs

Closes #1120 です。
全角スペースでごまかしています。

fix: can't unset the default value for bool parameter

---

Editor/Inspector/MaterialSetter/MaterialSetterStyles.uss
Editor/Inspector/MaterialSetter/MaterialSwitchObjectEditor.uxml
Editor/Inspector/ObjectToggle/ObjectSwitcherStyles.uss
Editor/Inspector/ObjectToggle/ToggledObjectEditor.uxml
Editor/Inspector/Parameters/ParameterConfigDrawer.cs
Editor/Inspector/Parameters/ParameterConfigDrawer.uxml
Editor/Inspector/Parameters/Parameters.uss
Editor/Inspector/ShapeChanger/ChangedShapeEditor.cs
Editor/Inspector/ShapeChanger/ChangedShapeEditor.uxml
Editor/Inspector/ShapeChanger/ShapeChangerStyles.uss

Shape Changer に対象のレンダラーにないブレンドシェイプ名が設定されていた場合、Material Setter と同じように文字を赤くするようにしました。
また、Reactive Components と MA Parameters の UI レイアウトのばらつきが気になったので、uss を整理しつつ調整しました。

Refine some UI

---

Editor/Animation/AnimatorCombiner.cs

Fix copy logic of sync layer

---

Editor/HeuristicBoneMapper.cs

Rigifyで追加されるボーン名(metarigの物)を追加
ミコジンちゃん
https://booth.pm/ja/items/5699843
にて動作確認

fix: add Rigify(metarig) bone mapping pattern

---

Editor/ScaleAdjuster/ScaleAdjusterPreview.cs

fix: Add null checks to ScaleAdjusterPreview

---

Editor/Inspector/Menu/MenuPreviewGUI.cs
Editor/Inspector/Menu/ToggleCreatorShortcut.cs
Runtime/ModularAvatarMenuItem.cs
Runtime/ModularAvatarMergeAnimator.cs
Runtime/RuntimeUtil.cs

Plugins that add Menu Item may break in non-playmode builds

---

Editor/ReactiveObjects/ParameterAssignerPass.cs
UnitTests~/ReactiveComponent.meta
UnitTests~/ReactiveComponent/ParameterAssignment.meta
UnitTests~/ReactiveComponent/ParameterAssignment/AutoValueAssignmentTests.cs
UnitTests~/ReactiveComponent/ParameterAssignment/AutoValueAssignmentTests.cs.meta

fix: multiple issues with auto parameter value assignment

---

Editor/Inspector/MaterialSetter/MaterialSetterEditor.cs
Editor/Inspector/MoveIndependently/MoveIndependentlyEditor.cs
Editor/Inspector/ObjectToggle/ObjectSwitcherEditor.cs
Editor/Inspector/ShapeChanger/ShapeChangerEditor.cs

fix: exception thrown when opening prefab override ui

---

Editor/Inspector/Parameters/DefaultValueField.cs
Editor/Inspector/Parameters/ParameterConfigDrawer.cs
Editor/Inspector/Parameters/Parameters.uss

Closes #1124 ですが、対応ブランチを main から切ると #1119 と #1121 とコンフリクトするため、このブランチには一旦これら 2 件の PR のコミットを含めています。
上記 2 件の PR がそのままマージされたらこのブランチを rebase して force push する予定です。(マージされなかったら書き直します)

Enhance default value field

---

Editor/ReactiveObjects/ParameterAssignerPass.cs
UnitTests~/ReactiveComponent/ParameterAssignment/AutoValueAssignmentTests.cs

fix: incorrect default value for single menu item with automatic value

---

Editor/ReactiveObjects/ParameterAssignerPass.cs
Editor/RenameParametersHook.cs

Fix parameter synced conflict

---

Editor/ParamsUsage/MAParametersIntrospection.cs
Editor/ReactiveObjects/ParameterAssignerPass.cs
Runtime/ModularAvatarMenuItem.cs
UnitTests~/ReactiveComponent/ParameterAssignment/ParameterTypeTests.cs
UnitTests~/ReactiveComponent/ParameterAssignment/ParameterTypeTests.cs.meta

Closes #1139 です。
ParameterValueLo / ParameterValueHi がこれでいいのかは微妙ですが、小数の判定が 0.01f だったので +0.005f/-0.005f にしてみました。

Fix menu item float value

---

Runtime/ModularAvatarBlendshapeSync.cs

fix: blendshape sync reserializes prefab assets

---

Editor/ApplyAnimatorDefaultValuesPass.cs

fix: animator initial value type conversion

---

Editor/HeuristicBoneMapper.cs

fix: add pattern of "upper_chest" as a chest bone

---

Editor/Inspector/Menu/MenuItemGUI.cs

Cache parameter introspection results (using PropCache) to avoid excessive
recomputation.
Closes: #1165

fix: performance issues with MAMenuItem

---

Editor/ScaleAdjuster/ScaleAdjusterPreview.cs

fix: Scale Adjuster preview breaks after changing scale of avatar root

---

Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs

fix: remove unnecessory exit transitions for reactive components

---

Editor/Menu/VirtualMenu.cs

fix: MenuInstaller does not support cloning (#1173)

---

Editor/Inspector/BoneProxyEditor.cs
Runtime/ModularAvatarBoneProxy.cs

fix: #627 
nullを受け付けていなかったので直しました。多分これで良いはず…!

fix: BoneProxy target couldn't be empty after assigned (#627)

---

Editor/MergeAnimatorProcessor.cs
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs

fix: reactive components break WD ON avatars

---

Editor/Animation/AnimationUtil.cs

fix: cloned AnimatorController is not registered in ObjectRegistry

---

Editor/ReactiveObjects/Simulator/ROSimulator.cs

fix: ROSimulator UI refresh sometimes gets wedged

---

Editor/Animation/AnimatorCombiner.cs

fix: play audio path mapping is broken

---

Runtime/ReactiveObjects/ModularAvatarMaterialSetter.cs
Runtime/ReactiveObjects/ModularAvatarObjectToggle.cs
Runtime/ReactiveObjects/ModularAvatarShapeChanger.cs

docs: fix reactive component help URL link

---

Editor/ReactiveObjects/AnimationGeneration/ReactionRule.cs
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectAnalyzer.cs
UnitTests~/ShapeChanger/InitialStates/SCDefaultAnimation.prefab

fix(rc): constant-off objects are not handled correctly

---

Editor/ReactiveObjects/ShapeChangerPreview.cs

fix: shape changer preview overrides default blendshape values inappropriately

---

README.md

docs: ドキュメントへの誘導を微調整

---

Editor/Animation/AnimationDatabase.cs
UnitTests~/MergeAnimatorTests/ProxyAnim.meta
UnitTests~/MergeAnimatorTests/ProxyAnim/New Animator Controller.controller
UnitTests~/MergeAnimatorTests/ProxyAnim/New Animator Controller.controller.meta
UnitTests~/MergeAnimatorTests/ProxyAnim/ProxyAnimTest.cs
UnitTests~/MergeAnimatorTests/ProxyAnim/ProxyAnimTest.cs.meta
UnitTests~/MergeAnimatorTests/ProxyAnim/ProxyAnimTest.prefab
UnitTests~/MergeAnimatorTests/ProxyAnim/ProxyAnimTest.prefab.meta

This fixes issues with しゃがみ置き換え＋α among other things.

fix: proxy animations are cloned in Merge Animator

---

Editor/ReactiveObjects/AnimationGeneration/AnimatedProperty.cs
Editor/ReactiveObjects/AnimationGeneration/ControlCondition.cs
Editor/ReactiveObjects/AnimationGeneration/ReactionRule.cs
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectAnalyzer.LocateReactions.cs
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectAnalyzer.cs

fix: propagate shape changer effects through BlendshapeSync

---

Editor/Localization/en-US.json

fix: missing localization strings for Replace Object errors

---

Editor/Animation/AnimatorCombiner.cs

fix: NRE when `AnimatorControllerLayer.stateMachine` is null

---

Editor/Animation/GameObjectDisableDelayPass.cs

fix: occasionally objects controlling reactive components "flicker"

---

Editor/Animation/GameObjectDisableDelayPass.cs
UnitTests~/ReactiveComponent/ObjectToggleTests.cs
UnitTests~/ReactiveComponent/ObjectToggleTests.cs.meta

fix: always-on toggles fail to animate objects to off

---

Editor/Inspector/Parameters/DefaultValueField.cs

fix: parameters lose their default value when others are moved around

---

Editor/Inspector/Menu/MenuInstallerEditor.cs

fix: "extract menu to objects" does not set the target of its menu group properly

---

Runtime/MAMoveIndependently.cs

fix: NRE when Move Independently is placed on a scene root

---

Editor/SetupOutfit.cs

chore: Add mesh settings regardless of parent presence in Setup Outfit

---

Editor/ObjectReferenceFixer.cs

Not sure if this will do anything, but maybe it'll help with the perf issues people have reported?

fix: suppress ObjectReferenceFixer in play mode

---

Editor/ReactiveObjects/ParameterAssignerPass.cs
UnitTests~/ReactiveComponent/ParameterAssignment/AutoValueAssignmentTests.cs

fix: MA Parameters bool items + MA Menu Item auto value is broken

---

Editor/ParamsUsage/MAParametersIntrospection.cs
Editor/RenameParametersHook.cs
UnitTests~/RenameParametersTests/RenameParametersTests.cs

fix: NotSynced parameters become synced when merging

---

Editor/Inspector/Menu/MenuItemGUI.cs

feat: allow multi-edit of "Is Default" when parameter names are empty

---

Editor/Inspector/MoveIndependently/MoveIndependentlyEditor.cs
Editor/PluginDefinition/PluginDefinition.cs
Runtime/ArmatureAwase/MoveIndep.meta
Runtime/ArmatureAwase/MoveIndep/MAMoveIndependentlyManager.cs
Runtime/ArmatureAwase/MoveIndep/MAMoveIndependentlyManager.cs.meta
Runtime/ArmatureAwase/NativeMemoryManager.cs
Runtime/MAMoveIndependently.cs

Fixed issues with nested Move Independently components (Closes #1367).
Fixed MAMoveIndependently not being saved (Supercedes #1366)
Reduce jittering when moving MAMI bones.

fix: multiple issues with MAMoveIndependently

---

Editor/MeshSettingsPass.cs

fix: changed not to use Instantiate when creating inverse root bone

---

Editor/Inspector/Menu/MenuInstallerEditor.cs
Runtime/Menu/ModularAvatarMenuInstaller.cs

feat: add API to open Menu Installer's selection UI

---

Editor/Inspector/Menu/MenuItemGUI.cs

fix: NullReferenceException in some cases when viewing MA Menu Item controls

---

Runtime/ArmatureAwase/MoveIndep/MAMoveIndependentlyManager.cs

fix: issues with MAMoveIndependentlyManager error handling

---

Editor/Inspector/AvatarObjectReferenceDrawer.cs

なさそうだったので追加しました
何か意図があって追加してなかったのなら蹴っちゃってください🙇

fix: add BeginProperty to AvatarObjectReferenceDrawer

---

Editor/FixupPasses/FixupExpressionsMenuPass.cs

#434 の修正が子メニューにかかってなかったので修正しました。
Fix #433 again
Fix #1294

fix: menu icon in submenu are not fixed

---

Editor/BuildContext.cs
Editor/Menu/VirtualMenu.cs
Editor/RenameParametersHook.cs
UnitTests~/RenameParametersTests/MenuItem-SubMenuIsRenamed-Issue1414.meta
UnitTests~/RenameParametersTests/MenuItem-SubMenuIsRenamed-Issue1414/Issue1414.prefab
UnitTests~/RenameParametersTests/MenuItem-SubMenuIsRenamed-Issue1414/Issue1414.prefab.meta
UnitTests~/RenameParametersTests/MenuItem-SubMenuIsRenamed-Issue1414/MenuItemSubmenusAreRenamed.cs
UnitTests~/RenameParametersTests/MenuItem-SubMenuIsRenamed-Issue1414/MenuItemSubmenusAreRenamed.cs.meta
UnitTests~/RenameParametersTests/MenuItem-SubMenuIsRenamed-Issue1414/TestMenu.asset
UnitTests~/RenameParametersTests/MenuItem-SubMenuIsRenamed-Issue1414/TestMenu.asset.meta
UnitTests~/RenameParametersTests/MenuItem-SubMenuIsRenamed-Issue1414/TestParameter.asset
UnitTests~/RenameParametersTests/MenuItem-SubMenuIsRenamed-Issue1414/TestParameter.asset.meta

fix: menu assets referenced by Menu Installer aren't renamed correctly

---

Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectAnalyzer.LocateReactions.cs

fix: RCs can't be used in conjunction with custom animations

---

Editor/MergeArmatureHook.cs
UnitTests~/MergeArmatureTests/MergeArmatureTests.cs

... apparently auto-merge wasn't set properly to check for unit test completion. oops.

fix: test failures in Merge Armature

---

.github/workflows/perform-release.yml
CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md

ci: fix missing logo assets

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/WorldFixedObjectProcessor.cs
UnitTests~/WorldFixedObjectTest/WorldFixedObjectTest.cs

feat: World Fixed Object now uses VRCParentConstraint and supports Android builds

---

.github/ProjectRoot/vpm-manifest-2022.json
CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
package.json

chore(deps): Update NDMF dependency

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/Animation/GameObjectDisableDelayPass.cs
UnitTests~/ReactiveComponent/DelayDisablePruningTest.cs
UnitTests~/ReactiveComponent/DelayDisablePruningTest.cs.meta
UnitTests~/ReactiveComponent/DelayDisablePruningTest.prefab
UnitTests~/ReactiveComponent/DelayDisablePruningTest.prefab.meta

fix: DelayDisable unnecessarily tracks no-longer-relevant game objects

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
Editor/OptimizationPasses/ConstraintConverterPass.cs

fix: convert constraints fails to convert animations

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
Editor/MergeAnimatorProcessor.cs
UnitTests~/MergeAnimatorTests/WriteDefaults/TestSet_true.controller
UnitTests~/MergeAnimatorTests/WriteDefaults/WriteDefaultsMergeTests.cs

fix: match WD = off setting is not respected

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/RenameParametersHook.cs
UnitTests~/RenameParametersTests/RenameParametersTests.cs

feat: MA Parameters auto-rename now uses stable names

---

.github/ProjectRoot/vpm-manifest-2022.json
CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
Editor/PluginDefinition/PluginDefinition.cs
package.json

The early animator cloning logic was dropped in refactoring, put it back.

fix: compatibility issue with lilycalInventory

---

.github/ProjectRoot/vpm-manifest-2022.json
CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/RenameParametersHook.cs
Runtime/ModularAvatarMergeBlendTree.cs
UnitTests~/RenameParametersTests/RenameParametersTests.cs
UnitTests~/RenameParametersTests/RenamesParameterCurves.anim
UnitTests~/RenameParametersTests/RenamesParameterCurves.anim.meta
UnitTests~/RenameParametersTests/RenamesParameterCurves.controller
UnitTests~/RenameParametersTests/RenamesParameterCurves.controller.meta
UnitTests~/RenameParametersTests/RenamesParameterCurves.prefab
UnitTests~/RenameParametersTests/RenamesParameterCurves.prefab.meta
package.json

fix: animated parameters in merge motion aren't renamed

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/RenameParametersHook.cs
Runtime/ModularAvatarMergeBlendTree.cs
UnitTests~/RenameParametersTests/NullVirtualizedComponents.prefab
UnitTests~/RenameParametersTests/NullVirtualizedComponents.prefab.meta
UnitTests~/RenameParametersTests/RenameParametersTests.cs

fix: KeyNotFoundException when MAMergeAnimator or MergeMotion reference is null

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/ReactiveObjects/MaterialSetterPreview.cs

fix: preview differed from the build result when multiple Material Setters conflicted

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/Util.cs
Runtime/ModularAvatarBlendshapeSync.cs
Runtime/RuntimeUtil.cs

fix: BlendshapeSync does not work in edit mode when inactive

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/MergeAnimatorProcessor.cs
UnitTests~/MergeAnimatorTests/WriteDefaults/TestSet_false.controller
UnitTests~/MergeAnimatorTests/WriteDefaults/TestSet_true.controller
UnitTests~/MergeAnimatorTests/WriteDefaults/blendtree.asset

fix: don't force non-direct blend trees to be WD=ON

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
Editor/Inspector/MaterialSwap/MaterialSwapEditor.cs
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectAnalyzer.LocateReactions.cs

material swap small fixes

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Runtime/ModularAvatarMenuItem.cs
UnitTests~/MenuItem/MenuItemSerializationTest.cs

closes #1681
VRC SDK環境における、Parameter, SubParameters, Labelsのgetterを修正します。

fix: PortableMenuControl may throw NullReferenceException

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/Animation/MMDRelayPass.cs
UnitTests~/Animation/LayerPruningTest.cs
UnitTests~/Animation/MMD/MMDHandlingTests.cs
UnitTests~/Animation/MMD/MMDMode_OptInFirstLayer.prefab
UnitTests~/Animation/MMD/MMDMode_OptInFirstLayer.prefab.meta
UnitTests~/Animation/MMD/OptIn.controller
UnitTests~/Animation/MMD/OptIn.controller.meta
UnitTests~/Animation/MergeBlendTreeTest.cs
UnitTests~/Animation/MergeOrderTest.cs

fix: layer #0 can't be opted into MMD disabling

---

Runtime/ReactiveObjects/ModularAvatarMeshCutter.cs

fix: MA Mesh Cutter was missing the MA prefix

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
Editor/ReactiveObjects/MeshDeleterPreview.cs

fix: O(n^2) processing in mesh cutter preview logic

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
Editor/Inspector/ScaleAdjusterTool.cs

fix: exceptions and information loss when scale adjusting to zero

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
Editor/ReactiveObjects/MeshDeleterPreview.cs

fix: incorrect renderer reference used for mesh deleter preview

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/MergeAnimatorProcessor.cs
Editor/MergeBlendTreePass.cs
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs

This could result in failure to correct for parameter type changes in parameter drivers.

fix: improper handling of AnimatorControllerParameters
