Packages/net.fushizen.modular-avatar/Editor/ApplyOnPlay.cs

As part of our hook processing, we destroy modular-avatar components; however, when entering play mode (without av3emu), these components might be prefab assets. To avoid scary unity errors, unpack these prefabs when entering play mode.

Avoid scary errors when entering play mode

---

Packages/net.fushizen.modular-avatar/Editor/MergeArmatureHook.cs

When a PB references a bone controlled by a constraint, the subtree rooted at that bone will be present only on the original armature tree, and not in the avatar's main armature tree (except for a stub object that may or may not be used for a constraint reference).
Previously, there was a bug in which PBs would reference the stub object, rather than the object that contains the bones that need to be animated by PBs. This commit changes the order of processing so bones are only registered for rewriting PB referenced if their subtrees will be transferred to the main armature.

Fix PBs referencing constrained bones not working

---

Packages/nadena.dev.modular-avatar/Editor/Inspector/AvMenuTreeView.cs

I felt that this type of selection window should close automatically when it loses focus.
(For example, a selection window for an ObjectField, etc.).
Now I could make it close automatically when it loses focus, but I think I could also get closer by using `ShowAuxWindow`.

Added support for closing AvMenuTreeViewWindow automatically when it loses focus.

---

Packages/nadena.dev.modular-avatar/Editor/Inspector/MenuInstallerEditor.cs
Packages/nadena.dev.modular-avatar/Editor/Localization/en.json
Packages/nadena.dev.modular-avatar/Editor/Localization/ja.json
Packages/nadena.dev.modular-avatar/Editor/Util.cs

The VRCSDK has a size limit and a compression setting limit for MenuIcon.
If there are icons in the MenuInstaller menu that exceed these limits, they are uploaded as they are.
The upload itself is normal, and there is no problem with VRC operation, but at least an error occurs in the performance window, so it would be better to at least send an error to MenuInstaller.
Depending on the situation, it may be necessary to remove the icon or make an error when building, but since the menu settings themselves are the responsibility of the asset creator, it may be better to simply warn the author so as not to cause confusion among asset users.

Add validation for menu icons.

---

Packages/nadena.dev.modular-avatar/Editor/AnimatorMerger.cs
Packages/nadena.dev.modular-avatar/Editor/RenameParametersHook.cs
Packages/nadena.dev.modular-avatar/Editor/Util.cs

#138 
Added process to convert `AnimatorOverrideController` to `AnimatorController` during `Animator` and `ModularAvatarMergeAnimator` processes of `RenameParametersHook`.

Support for AnimatorOverrideController

---

Packages/nadena.dev.modular-avatar/Editor/MergeArmatureHook.cs

The Merge Armature logic is in need of an overall rewrite, but this works around
issues where added (duplicate) bones break PBs in parents, by adding these to parent PB ignore lists.

Workaround Merge Armature breaking parent PBs

---

Packages/nadena.dev.modular-avatar/Editor/AnimatorMerger.cs
Packages/nadena.dev.modular-avatar/Editor/AvatarProcessor.cs
Packages/nadena.dev.modular-avatar/Editor/BlendshapeSyncAnimationProcessor.cs
Packages/nadena.dev.modular-avatar/Editor/BuildContext.cs
Packages/nadena.dev.modular-avatar/Editor/MenuInstallHook.cs
Packages/nadena.dev.modular-avatar/Editor/MergeAnimatorProcessor.cs
Packages/nadena.dev.modular-avatar/Editor/MergeArmatureHook.cs
Packages/nadena.dev.modular-avatar/Editor/MeshRetargeter.cs
Packages/nadena.dev.modular-avatar/Editor/RenameParametersHook.cs
Packages/nadena.dev.modular-avatar/Editor/Util.cs

CreateAsset, as it turns out, can be extremely slow, particularly when used on Mesh objects.
By adding our generated objects as sub-objects of a container AnimatorController, we can
minimize this overhead.

fix: improve build performance by ~10x

---

Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping.meta
Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping/DuplicatePBStripping.cs
Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping/DuplicatePBStripping.cs.meta
Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping/DuplicatePBStripping_nullRef.prefab
Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping/DuplicatePBStripping_nullRef.prefab.meta
Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping/DuplicatePBStripping_objRef.prefab
Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping/DuplicatePBStripping_objRef.prefab.meta
Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping/DuplicatePBStripping_otherRef.prefab
Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping/DuplicatePBStripping_otherRef.prefab.meta
Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping/DuplicatePBStripping_preserve.prefab
Assets/_ModularAvatar/EditModeTests/DuplicatePBStripping/DuplicatePBStripping_preserve.prefab.meta
Packages/nadena.dev.modular-avatar/Editor/MergeArmatureHook.cs

The previous logic failed when duplicate PBs explicitly specify their root transform.
This change rewrites this logic and expands the cases in which PBs are pruned.

fix: duplicate PB stripping fails in some configurations

---

Assets/_ModularAvatar/EditModeTests/MiscAnimationTests.meta
Assets/_ModularAvatar/EditModeTests/MiscAnimationTests/HQ_OFF.anim
Assets/_ModularAvatar/EditModeTests/MiscAnimationTests/HQ_OFF.anim.meta
Assets/_ModularAvatar/EditModeTests/MiscAnimationTests/HQ_ON.anim
Assets/_ModularAvatar/EditModeTests/MiscAnimationTests/HQ_ON.anim.meta
Assets/_ModularAvatar/EditModeTests/MiscAnimationTests/HighQualityCurvesSettingPreserved.controller
Assets/_ModularAvatar/EditModeTests/MiscAnimationTests/HighQualityCurvesSettingPreserved.controller.meta
Assets/_ModularAvatar/EditModeTests/MiscAnimationTests/HighQualityCurvesSettingPreserved.prefab
Assets/_ModularAvatar/EditModeTests/MiscAnimationTests/HighQualityCurvesSettingPreserved.prefab.meta
Assets/_ModularAvatar/EditModeTests/MiscAnimationTests/MiscAnimationTests.cs
Assets/_ModularAvatar/EditModeTests/MiscAnimationTests/MiscAnimationTests.cs.meta
Packages/nadena.dev.modular-avatar/Editor/AnimationDatabase.cs
ProjectSettings/GraphicsSettings.asset

This setting is set to _off_ on some imported animation files;
in this case, tangent data is not used and the curve is interpolated linearly.
Previously, we would sometimes set this to on as part of various animation
manipulations we perform in MA processing; this broke some avatars, e.g. "Fluria".

fix: high quality curve setting is not preserved properly

---

Packages/nadena.dev.modular-avatar/Editor/Inspector/Menu/MenuInstallerEditor.cs

Fix #281 
空のSubMenuを持つアバターにおいて、MenuInstallerのInspector表示をするとNullReferenceExceptionを吐くことの修正です。

空のSubMenuがあるとMenuInstallerの表示でエラーが発生するのを修正

---

Packages/nadena.dev.modular-avatar/Editor/Menu/ActionProcessing/ActionGenerator.cs

Fix #279 
Meshが空のSkinnedMeshRendererがアバター内にある際、ActionGeneratorがNullReferenceExceptionを吐くことの修正です。

Meshが空のSkinnedMeshRendererがあるとActionGeneratorがエラーを起こすのを修正

---

Packages/nadena.dev.modular-avatar/Runtime/Menu/VirtualMenuAPI.cs

VirtualControlのコンストラクタでlabelsやsubParametersがnullの場合null条件演算子でnullチェックされていますが、その後の処理ではnullチェックされていないため、NullReferenceExceptionが発生します。
そのため、nullの際は空の配列へ置き換える処理を追加しました。

ControlのlabelsやsubParametersがnullの場合エラーが発生する不具合の修正

---

Packages/nadena.dev.modular-avatar/Editor/Inspector/AvatarParametersEditor.cs

Fix #333 
パラメータを削除した際、 `AvatarParametersEditor.OnInnerInspectorGUI()` の `BuildHeightCache` で未更新の_selectedIndicesを見るためout of boundsが発生しています。
ReorderableListの描画までにElementHeightCacheを更新出来ればよいと思われるため、SetupList()が叩かれた後に移動しました。

Change timing of BuildHeightCache

---

Packages/nadena.dev.modular-avatar/Editor/Menu/ActionProcessing.meta

empty folders are not tracked by git so such a meta file will be removed by unity on loading

chore: remove meta file for empty folder

---

Packages/nadena.dev.modular-avatar/Editor/MeshSettingsPass.cs

ArmatureやBoneがない状態のSkinnedMeshRendererにRootBoneを指定すると、描画位置がRootBoneの場所へ移動してしまう問題の修正です。
自身のTransformをボーンとして登録したメッシュを生成する事で対策を行いました。

 ボーンが存在しないSkinnedMeshRendererでRootBoneを設定すると描画位置がずれる問題の修正

---

Packages/nadena.dev.modular-avatar/Editor/MergeAnimatorProcessor.cs

fix: hands mask not set when merging if the initial configuration used the default

---

Assets/_ModularAvatar/EditModeTests/VirtualMenuTests/InternalParamTestMenu.asset
Assets/_ModularAvatar/EditModeTests/VirtualMenuTests/InternalParamTestMenu.asset.meta
Assets/_ModularAvatar/EditModeTests/VirtualMenuTests/InternalParameterTest.prefab
Assets/_ModularAvatar/EditModeTests/VirtualMenuTests/InternalParameterTest.prefab.meta
Assets/_ModularAvatar/EditModeTests/VirtualMenuTests/VirtualMenuTests.cs
Packages/nadena.dev.modular-avatar/Editor/Inspector/Menu/MenuPreviewGUI.cs
Packages/nadena.dev.modular-avatar/Editor/Menu/VirtualMenu.cs
Packages/nadena.dev.modular-avatar/Runtime/Menu/VirtualMenuAPI.cs

- chore: adding unit tests for #366 and #326
- fix: duplicate submenu controls not generated for multiple installers
- fix: submenus incorrectly deduping across different postprocessing contexts

fix: issues with multiple installers using the same expressions menu asset

---

Packages/nadena.dev.modular-avatar/Editor/EasySetupOutfit.cs
Packages/nadena.dev.modular-avatar/Editor/HeuristicBoneMapper.cs

The human avatar mapping system seems to use bone _names_ rather than full
_paths_ to identify bones. When the avatar armature and an outfit armature
are both present under the avatar root, this can result in misidentification
of outfit bones as avatar bones on the avatar animator. This in turn results
in issues with Bone Proxy's editor-side tracking logic.
This change adjusts setup outfit to ensure that there is always a prefix
and/or suffix set, renaming bones if necessary.
Note that this does not fully use outfit human avatar data to map bones yet;
this is mostly intended as a patch to resolve the issues that have been
reported recently, particularly around the stricter validations in SDK
3.3.0.

fix: avoid name collisions in setup outfit

---

Packages/nadena.dev.modular-avatar/Editor/EasySetupOutfit.cs

fix: [ESO] bounds are untransformed when root bone is inconsistent

---

Packages/nadena.dev.modular-avatar/Editor/EasySetupOutfit.cs
Packages/nadena.dev.modular-avatar/Editor/HeuristicBoneMapper.cs

This reverts commit 6cbcde05f4e14308792ea32ad799f011c42ff7fe.
Adding a suffix broke enough people's workflows that it's probably
better to look for a more targeted solution to the misbinding issue
(once we have a repro).

Revert "fix: avoid name collisions in setup outfit (#435)"

---

Editor/Inspector/InspectorCommon.cs

Related issue: #478
[PrefabStageUtility](https://docs.unity3d.com/2021.2/Documentation/ScriptReference/SceneManagement.PrefabStageUtility.html) is no longer [Experimental](https://docs.unity3d.com/2019.4/Documentation/ScriptReference/Experimental.SceneManagement.PrefabStageUtility.html) on Unity 2021.2 and above

chore: fix SceneManagement editor using

---

Runtime/ModularAvatarMergeArmature.cs

When an avatar is enabled after the scene is initially loaded, Merge Armature
would result in a lot of NullReferenceExceptions being logged.

fix: null reference errors when apply on play triggers late

---

CHANGELOG.md.meta
README.md.meta

when importing through a UPM registry like OpenUPM packages are immutable. So they should have all meta files included

add missing meta files

---

Editor/ActiveAnimationRetargeter.cs
Editor/BlendshapeSyncAnimationProcessor.cs
Editor/BuildContext.cs
Editor/EasySetupOutfit.cs
Editor/ErrorReporting/ErrorLog.cs
Editor/ErrorReporting/ErrorReportUI.cs
Editor/HeuristicBoneMapper.cs
Editor/Inspector/AvatarObjectReferenceDrawer.cs
Editor/Inspector/BlendshapeSyncEditor.cs
Editor/Inspector/BoneProxyEditor.cs
Editor/Inspector/FirstPersonVisibleEditor.cs
Editor/Inspector/InspectorCommon.cs
Editor/Inspector/MeshSettingsEditor.cs
Editor/MeshRetargeter.cs
Editor/PluginDefinition/ModularAvatarContext.cs
Editor/PluginDefinition/PluginDefinition.cs
Editor/Util.cs
Editor/VisibleHeadAccessoryProcessor.cs
Editor/WorldFixedObjectProcessor.cs
Runtime/AvatarObjectReference.cs
Runtime/ModularAvatarBoneProxy.cs
Runtime/ModularAvatarMergeArmature.cs
Runtime/RuntimeUtil.cs
Runtime/nadena.dev.modular-avatar.core.asmdef
UnitTests~/ReplaceObject/ReplaceObjectTests.cs
UnitTests~/WorldFixedObjectTest/WorldFixedObjectTest.cs

Related issue: #478 
As ndmf 1.2.0 has implemented some cross platform Avatar root handling APIs in bdunderscore/ndmf#34, we can make use of them before introducing `#if MA_VRCSDK3_AVATARS` version define to minimize the big bang diff.
- Utilize ndmf 1.2.0 API from in some of EditorContext and RuntimeUtil methods (The final commit is very aggressive!)
- Use them instead of `VRCAvatarDescriptor` everywhere
- except VRC animation layer handlers and menu handlers, because they are very VRC specific
- `VRCAvatarDescriptor` becomes either `BuildContext` or `Transform`, depending on context
This PR breaks a lot of internal APIs, which passes around `VRCAvatarDescriptor`, so this PR may be either directly merged or be used as a reference of what we should do and broken up into smaller PRs.

chore: use ndmf Avatar Root api where applicable

---

Editor/VisibleHeadAccessoryProcessor.cs

#513 に対するパッチで、#if を使ったものですが#if を使用したくない場合であれば、[UnityEditorのAPI](https://docs.unity3d.com/2019.4/Documentation/ScriptReference/EditorUserBuildSettings-activeBuildTarget.html) などがありそうなので、その場合はこの pull request はクローズしてください。

fix: Visible Head Accessory processing is effective when building for Quest standalone

---

Editor/Util.cs
UnitTests~/TestBase.cs

Context: https://github.com/bdunderscore/modular-avatar/pull/504#discussion_r1378615896
Simple cleaning up old code.
Did not remove `MAAssetBundle` and editor for now, changing it into subclass of `ndmf.runtime.GeneratedAssets` was more aggressive choice (which would delete more code).

Refactor: Delete unused code for MAAssetBundle generation

---

Editor/ParameterPolicy.cs

Some Physbone parameters are not recognized in MA Parameters, this cause internal parameter don't work those parameters, such as _IsPosed.
1. Create PhysBone Component and set parameter `param`
2. Create FXLayer and Add Parameter `param_IsPosed` and `param_Stretch`
3. Setup Modular Avatar, Merge Animator / MA Parameters
4. Switch to MA Parameters Developer mode, `param` is recognized PhysBones Prefix, but also detected `param_IsPosed` with no PhysBones Prefix.

fix: missing physbone parameter suffixes

---

Editor/MergeArmatureHook.cs
UnitTests~/MergeArmatureTests/MergeArmatureTests.cs
UnitTests~/MergeArmatureTests/PartiallySamePhysBoneChain.prefab
UnitTests~/MergeArmatureTests/PartiallySamePhysBoneChain.prefab.meta

Fixes #546
PBルートが同じ位置だけど子の位置等だけが大きく違う場合の問題を、マージする条件を子孫すべてが同じ位置の場合とすることで修正

fix: do not merge PhysBone chain if the chain is partially different

---

docs~/docs/reference/world-fixed-object.md
docs~/i18n/ja/docusaurus-plugin-content-docs/current/reference/world-fixed-object.md

現状はWorld Fixed ObjectをQuest向けビルドでは使用できないため(#581)、実際の動作に合わせてドキュメントを更新します。

docs(world-fixed-object): fix description for Quest

---

Editor/RenameParametersHook.cs

Sub-animators have an independent parameter namespace from the main avatar, so we shouldn't
rename them.

fix: Rename Parameters should not impact sub-animator components

---

Editor/Inspector/ScaleAdjusterTool.cs
Runtime/ScaleAdjuster/ScaleAdjusterRenderer.cs

- fix: undo operations can cause scale adjuster to perma-disable meshes
- fix: tool is left hidden after scale adjuster is deleted

fix: minor issues with scale adjuster

---

Editor/RenameParametersHook.cs
UnitTests~/RenameParametersTests/RenameParametersTests.cs

Fixed by allowing this case and applying normal parameter type resolution rules.
Closes: #694

fix: untranslated warning generated when multiple parameters remap to the same name

---

Editor/HarmonyPatches/PatchLoader.cs
Editor/HarmonyPatches/SnoopHeaderRendering.cs
Editor/HarmonyPatches/nadena.dev.modular-avatar.harmony-patches.asmdef
Runtime/ScaleAdjuster/ScaleAdjusterRenderer.cs
package.json

Harmony patches were not being loaded for VRCSDK 3.4.x, causing some issues with component enabled state checkboxes being incorrect.
Additionally, we need to reset component states before assembly reload and scene save.

fix: issues with Scale Adjuster on 2019

---

Runtime/ScaleAdjuster/ScaleAdjusterRenderer.cs

- fix: ScaleAdjuster causes console errors when a mesh is missing
- chore: hide ScaleAdjusterRenderer component

fix: ScaleAdjuster causes console errors when a mesh is missing

---

Editor/ApplyAnimatorDefaultValuesPass.cs

Fixed some compile errors I've found when using Modular Avatar in VRCSDK project with non-VRChat avatars, but for MA 1.9.4.
Note: Actually we don't need this PR until bdunderscore/ndmf#71 is merged, because AvatarRoot without VRCAvatarDescriptor in VRCSDK projects would not be allowed until then.

chore: Fix non-VRChat support

---

Editor/PluginDefinition/PluginDefinition.cs

AAO に警告出されること以外影響はなく、シーンをリロードでもすればこの問題は発生しませんが、あったほうが良いと私は思います。
とりあえずで MAMoveIndependently だけを指定して削除していますが、編集ツールのようなコンポーネントが今後増えるならインターフェース指定で削除する実装にしてもいいかもしれないですね！

MA MoveIndependently をMAの処理終了時にパージする

---

Editor/Animation/DeepClone.cs

Quick fix for the new [Animator Play Audio State Behavior](https://vrc-beta-docs.netlify.app/avatars/state-behaviors#animator-play-audio) available in SDK 3.5.2 Open Beta.

Fix For Audio Clip References in Animator

---

Runtime/ArmatureAwase/AllocationMap.cs
UnitTests~/ArmatureAwase/AllocationMapTest.cs

Zero-length allocations could result in multiple entries with the same offset in the segment map. This would then break subsequent lookups.
Fixed by increasing these allocations to a minimum length of one.

fix: FreeSegment "segment not found" errors

---

Editor/RenameParametersHook.cs

This creates compatibility issues with VRCF, as well as being
run in the wrong phase of processing in any case.
At some point this will need to be restored, as part of a new
NDMF processing phase that runs much later in the build.
Fixes: #813, #806

fix: disable parameter cost check for now

---

docs~/src/pages/index.module.css

Fixed an issue where button placement was disrupted when the document width is small. 
| before | after |
| --- | --- |
| ![image](https://github.com/bdunderscore/modular-avatar/assets/60507815/ff5cf34d-97f4-418f-935c-c10be16991ad) | ![image](https://github.com/bdunderscore/modular-avatar/assets/60507815/0988785c-741d-4165-af7f-6cf699425fe7) |
(images are not displayed due to preview issue)
Buttons now align vertically when document is switched to single column layout. Use grid instead of flexbox to match the width of each button when vertically aligned.

Fix mobile display of document top page

---

Editor/Animation/AnimationDatabase.cs
Editor/Animation/AnimatorCombiner.cs
Editor/Animation/PathMappings.cs
Editor/nadena.dev.modular-avatar.core.editor.asmdef

This is my attempt to implement handling source path inside `VRCAnimatorPlayAudio` for Modular Avatar. (#783, #858)
It is a quite dirty approach and don't know if the code quality is qualifiable to merge into upstream so I file a PR here anyways.
Before Animator Merging:
After Animator Merging:

Implement VRCAnimatorPlayAudio handling logic

---

.github/workflows/build-release.yml

With bdunderscore/vpm-repo-list-generator#318, zipSHA256 support will be added

ci: add zipSHA256 support

---

Editor/ScaleAdjusterPass.cs

Scale Adjuster introduces child transforms, and thus needs to add PB exclusions
to avoid breaking parent PB chains.
Closes: #924

fix: Scale Adjuster breaks physbones

---

Editor/Animation/PathMappings.cs

fix: cursed interaction with Unity Timeline causes animation curves to be lost

---

Editor/HeuristicBoneMapper.cs

"びしょぬれのしずくさん"のボーン名が辞書に入っていないため、Setup Outfit等が正常に動作しない問題の修正を試みます。
fix: #874
現状の懸念点
- Armatureが"bone_root"であることが(他コンポーネント/処理含めて)想定されているかが不明
- アバター側のボーンにprefixがついていることが想定されているかが不明
- 想定されていない場合、prefixを含めたボーン名に修正する必要があります(アバター側の全てのボーンに"bone_"が付いているため)が、あまり現実的ではないような…
- lowerlegに"leg_L"及びRを追加しましたが、upperlegに"Leg_L"及びRが存在するため、正常に処理されるか自信がありません。手元で動かした感じでは大丈夫そうでしたが…
- 当該アバター/衣装を持っていないため、実環境でのテストが出来ていない

fix: add heuristic bone mapping pattern

---

Editor/ReactiveObjects/ParameterAssignerPass.cs

- Don't create parameters for submenus and puppets automatically
- Create parameters when the menu item and RC are on the same GameObject

fix: multiple issues in autocreate parameter heuristics

---

Editor/PluginDefinition/PluginDefinition.cs
Editor/RebindHumanoidAvatar.cs
Editor/RebindHumanoidAvatar.cs.meta

Closes #1036 
`Animator.avatar` 再設定前にアバター内の Transform のローカル値を全て保存し、再設定後に復元する。

Preserve local transform when rebinding humanoid avatar

---

Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs

Closes #1122 です。
(本件とは関係ないですが、アセット名やパスの DisplayName が Reactive Components 全般を指す名前ではなく `Shape Changer` になっているのが少し気になっています)

fix: warning when object name contains "."

---

Editor/ScaleAdjuster/ScaleAdjusterPreview.cs

Might fix: https://github.com/bdunderscore/modular-avatar/issues/1055

fix: ScaleAdjusterPreview breaks when avatar descriptors are nested

---

Editor/Animation/AnimationDatabase.cs
Editor/Animation/DeepClone.cs

This resulted in data loss when `AssetDatabase.StopAssetEditing()` was called, which can happen if VRCF triggers Poi lockdown.

fix: animation clips are not added to the persistent asset object on build

---

Editor/SetupOutfit.cs

fix: #1196 
(ちなみに、変更点の真上の行に使用されていない"obj"変数の宣言があるようですが、消し忘れでしょうか…?)
(a bit related to #1195 ?)

fix: Setup Outfit cause NRE when nothing selected

---

Editor/Inspector/FirstPersonVisibleEditor.cs

improve: #599 
issueをcloseするかどうかはお任せします。
https://github.com/bdunderscore/modular-avatar/issues/599#issuecomment-2367449759 により、文言修正は今のところ行っていません。
BoneProxyの検知ですが、自身についていたら良いのですが、自身の親やその親がBoneProxyでHead以下に移動する場合などが想定されると思うので、(毎回親まで辿ることになるのは)負荷が高そうだな…と思って手を付けませんでした。

Visible Head Accessoryがhead以下にない時の表示をエラーから警告に変更

---

Editor/MergeAnimatorProcessor.cs

fix: ignore blendtree-only layers when determing animator WD state

---

Editor/PluginDefinition/PluginDefinition.cs
UnitTests~/VirtualMenuTests/VirtualMenuTests.cs

Changes to pass ordering caused Merge Armature to destroy menus before being
processed by Menu Installer; fix this by hoisting menu generation to occur within
the animation services context, before Merge Armature runs. This is safe because
the menu installer pass does not interact with the avatar's animator controllers
directly.

fix: Menu Installers on the same object as Merge Armature are not processed

---

Runtime/ReactiveObjects/ModularAvatarShapeChanger.cs
UnitTests~/ShapeChanger/InitialStates/SCDefaultAnimation.prefab

ベータ期間中だけの予定だった ShapeChanger のマイグレーション処理、すっかり忘れていました。

chore: remove ShapeChanger migration for beta only

---

Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs

This reverts commit 9dfa0dae23d9d4aa6e80e9c9d691e363dc297fdc. Those
transitions are needed when controlling the same object from multiple
parameters.
Closes: #1234

Revert "fix: remove unnecessory exit transitions for reactive components (#1161)"

---

docs~/src/pages/index.module.css
docs~/src/pages/index.tsx

Closes: #1260 
On documentation top page, I deletead unnececcary `button-group`. Details are explained in https://github.com/bdunderscore/modular-avatar/issues/1260.

docs: delete button group on top page

---

Editor/Inspector/DragAndDropManipulator.cs
Editor/Inspector/DragAndDropManipulator.cs.meta
Editor/Inspector/MaterialSetter/MaterialSetterEditor.cs
Editor/Inspector/MaterialSetter/MaterialSetterStyles.uss
Editor/Inspector/ObjectToggle/ObjectSwitcherEditor.cs
Editor/Inspector/ObjectToggle/ObjectSwitcherStyles.uss
Editor/Inspector/ShapeChanger/ShapeChangerEditor.cs
Editor/Inspector/ShapeChanger/ShapeChangerStyles.uss

MA Material Setter と MA Shape Changer の D&D 対応です。
MA Object Toggle と共通化しています。
リストが空でないときに範囲が狭すぎてドロップしづらかったので外枠まで広げてみました。
マウスカーソルが映っていませんがドロップしようとしているときのスクショです。

feat: add support for drag-and-drop on MaterialSetter and ShapeChanger

---

Editor/SetupOutfit.cs

- fix: #1186
- fix: #1198 
Setup Outfitが呼ばれた際、
- 設定済みでも統合先などが空orアバターに含まれないものである場合、再設定します
- 設定済みでもprefix/suffixが空の場合、InferPrefixSuffixを行います
- 常にRenameBoneByHeuristicを行います
- subRootの再確認もします
- MeshSettingsも同様にします
副産物として、Setup OutfitのUndo History表記を"Setup Outfit"にしました。
#1167 とconflictするかも?

feat: improve behavior when called setup outfit for setuped outfit

---

Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs
Editor/ReactiveObjects/ParameterAssignerPass.cs

This PR attempts to fixes #1299 
The issue causing type mismatch is it doesn't do type checking when generating new states, and re-using existing AnimatorCombiner class might be just good enough here.
(P.S. This is a quick fix as this issue also affects Hatch Menu, one of my gimmick with an installer that uses Modular Avatar)

Fixes error when merging same parameter with different type in RC menu item

---

Editor/Animation/AnimationDatabase.cs
Editor/Animation/AnimationServicesContext.cs
Editor/Animation/AnimationUtil.cs
Editor/Animation/PathMappings.cs
Editor/FixupPasses/FixupExpressionsMenuPass.cs
Editor/MergeAnimatorProcessor.cs
Editor/OptimizationPasses/PruneParametersPass.cs
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs
Editor/RenameParametersHook.cs
UnitTests~/Animation/AnimParameterPathRewrite/AnimParameterPathRewritingTest.cs
UnitTests~/Animation/AvatarMask/AvatarMaskTest.cs
UnitTests~/Animation/BaseLayerReferenceCorrection/BaseLayerReferenceCorrectionTest.cs
UnitTests~/Animation/PlayAudio/PlayAudioRemapping.cs
UnitTests~/MergeAnimatorTests/MergeSingleTests.cs
UnitTests~/MergeAnimatorTests/PreexistingAnimatorParams/PreexistingParamsTest.cs
UnitTests~/MergeAnimatorTests/ProxyAnim/ProxyAnimTest.cs
UnitTests~/MergeAnimatorTests/SyncedLayerOverrideInSubStatemachine/SyncedLayerOverrideInSubStateMachine.cs
UnitTests~/MergeAnimatorTests/TypeAdjustment/ConvertTransitionTypes.cs
UnitTests~/MergeDBT/MergeDirectBlendTreeTests.cs
UnitTests~/ReactiveComponent/BlendshapeSyncTest.cs
UnitTests~/ReactiveComponent/ObjectToggleTests.cs
UnitTests~/ReactiveComponent/ParameterAssignment/AutoValueAssignmentTests.cs
UnitTests~/ReactiveComponent/ParameterAssignment/ParameterTypeTests.cs
UnitTests~/ReactiveComponent/ShapeDeletionAnalysis.cs
UnitTests~/ShapeChanger/InitialStates/SCDefaultAnimation.cs
UnitTests~/VisibleHeadAccessoryTest/VisibleHeadAccessoryTest.cs

Improved non-VRChat projects and non-VRChat avatars (in VRCSDK projects) support, but for MA 1.10.5.

chore: Fix non-VRChat support (for MA 1.10.5)

---

Editor/Inspector/Parameters/AvatarParametersEditor.cs
Editor/Inspector/Parameters/ParameterConfigDrawer.cs
Editor/Inspector/Parameters/Parameters.uss
Editor/Inspector/Parameters/ParametersMainUI.uxml
Editor/Localization/en-US.json

* Add import-from-asset feature (Closes: #880, #668, #410)
* Limit size of scrollable area to avoid double-scrolling
* Add support for pressing the "delete" key to delete parameters.

ui: Improvements to MA Parameters editor

---

Editor/ReactiveObjects/ParameterAssignerPass.cs

fix: ParameterAssignerPass forces all parameters to float type

---

Editor/MergeArmatureHook.cs

[ctx-TreeRoot](https://misskey.niri.la/notes/a0ooh9xb8m)
[ctx](https://misskey.niri.la/notes/a0oserkoxu)
SkinnedMeshRenderer では RootBone のスケールが奇数個反転しているか否かは重要なパラメーターのようで、この部分のが奇数個反転していると Unity は カリングを反転させるようです。
スケールの反転を Mesh の方は(おそらくBonePoseを)補正することで問題がないように見えますが、RootBone は補正できないので、 RootBone を保持するようにする PR です！

fix: MA MergeArmature forget to retaining the root bone.

---

Editor/MeshSettingsPass.cs

[ctx](https://misskey.niri.la/notes/a0ouse7gd0) related #1355 
#1355  にて MA Merge Armature が RootBone を保持するようになって、反転した RootBone が保持されたとしても MA Mesh Settings がそれを破壊してしまうので MeshSettings にそれを維持させるようにする PR です！
具体的には 設定しようとしている RootBone と もともと割り当たってる RootBone を比較して、反転の値が一致していない場合に 設定しようとしている RootBone をクローンして反転して子としてわりてたものを生成しそれを、レンダラーに割り当てるようにしています。(バウンスも同時に反転するようにも補正しています。)

fix: MA MeshSettings forget to keep the inverse root bone.

---

Runtime/AvatarObjectReference.cs

fix: high load caused by ObjectReferenceFixer when paths collide

---

Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs

This results in downstream tools such as AAO improperly treating these objects as animated.

fix: deletedShape animation curves are retained in final avatar animations

---

Editor/MiscPreview/RemoveVertexColorPreview.cs
Editor/ScaleAdjuster/ScaleAdjusterPreview.cs

ScaleAdjusterとRemoveVertexColorのNDMF Preview GetTargetGroupsにおける多少のパフォーマンス改善を行うPRです。
自分の環境ではそれぞれおよそ60msから20msほどに短縮しています。
817390a950c6fc40abb775032393fad4843cde60 ではInactiveなRoot以下を処理の対象から除外しています。(`ctx.ActiveInHierarchy(root)`でobserveするので問題ないはず)
83843e039c366129ce349d6ecad9b0ebb837286d では不要と思われる行を削除しました(パフォーマンスへの影響は小さいと思います。不要なscaleAdjustersの取得を行っており、observeも後の行の`ctx.GetComponentsInChildren<ModularAvatarScaleAdjuster>`で行われていると思います。)
こちらの勘違いがあったらcloseしてもらって大丈夫です :bow:

perf: skip some preview process for ScaleAdjuster and RemoveVertexColor

---

Editor/Inspector/Menu/ToggleCreatorShortcut.cs
Runtime/UI/UnityMenuItems.cs

closes #1399 
不要な場合は閉じてもらって大丈夫です

feat: Create Toggle for Selection

---

Editor/MergeAnimatorProcessor.cs
UnitTests~/MergeAnimatorTests/MergeSingleTests.cs

Unity ignores the weight of the first layer in a controller, and forces it to one; here, we replicate that behavior in Merge Animator.
Note that we choose to do this here rather than in NDMF - this is because NDMF-level APIs are trying to accurately represent the data in the animator, and should be able to round-trip even "garbage" data there.
Closes: https://github.com/bdunderscore/ndmf/issues/534
Closes: #1472

fix: incorrect first layer weights in Merge Animator

---

Editor/RenameParametersHook.cs
UnitTests~/RenameParametersTests/RenameParametersTests.cs
UnitTests~/RenameParametersTests/RenamesTransitionParameters.controller
UnitTests~/RenameParametersTests/RenamesTransitionParameters.controller.meta
UnitTests~/RenameParametersTests/RenamesTransitionParameters.prefab
UnitTests~/RenameParametersTests/RenamesTransitionParameters.prefab.meta

[ctx](https://misskey.niri.la/notes/a4uvyuc69f) 
見たところ RenameParametersHook のところで、VirtualStateTransition は処理されないコードパスになっていてそれが原因で State同士のTransition が処理されていないように見えたので、ProcessTransition() が VirtualTransitionBase を引数に取るよのにならって Switch の部分で VirtualTransitionBase を case として取ることで正常に動作するようになったのでその実装です!

fix: forget to process VirtualStateTransition

---

Editor/Inspector/Parameters/AvatarParametersEditor.cs

Reference:
https://github.com/bdunderscore/modular-avatar/blob/242a108703545917eee6b0fd3fe0b57b42c7400a/Runtime/ModularAvatarParameters.cs#L45-L57

fix: Use `localOnly` instead of `syncType = NotSynced` when importing parameter asset

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/MergeArmatureHook.cs
UnitTests~/DuplicatePBStripping/DuplicatePBStripping.cs
UnitTests~/DuplicatePBStripping/DuplicatePBStripping_HumanoidInner.prefab
UnitTests~/DuplicatePBStripping/DuplicatePBStripping_HumanoidInner.prefab.meta
UnitTests~/DuplicatePBStripping/DuplicatePBStripping_HumanoidInner_Ignored.prefab
UnitTests~/DuplicatePBStripping/DuplicatePBStripping_HumanoidInner_Ignored.prefab.meta
UnitTests~/DuplicatePBStripping/DuplicatePBStripping_HumanoidInner_PBBlocker.prefab
UnitTests~/DuplicatePBStripping/DuplicatePBStripping_HumanoidInner_PBBlocker.prefab.meta
UnitTests~/DuplicatePBStripping/DuplicatePBStripping_HumanoidTip.prefab
UnitTests~/DuplicatePBStripping/DuplicatePBStripping_HumanoidTip.prefab.meta
UnitTests~/DuplicatePBStripping/DuplicatePBStripping_far.prefab
UnitTests~/DuplicatePBStripping/DuplicatePBStripping_preserve.prefab
UnitTests~/VisibleHeadAccessoryTest/VHA_shapell.prefab
UnitTests~/_CommonAssets/ShapellAvatar.prefab

This change adds support for merging humanoid bones that are a target of PhysBones, provided that all humanoid children are excluded from that PhysBone (either with a direct ignores field, or using PB Blocker).
Note: Because this is a significant expansion of support, this will need to wait for a minor release to maintain semver semantics.
Closes: #1406

feat: support merging humanoid bones with PBs in limited cases

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/Inspector/Parameters/AvatarParametersEditor.cs
Editor/Inspector/Parameters/ParameterConfigDrawer.cs

fix: unity editor shortcuts break while editing MA Parameters text fields

---

docs~/i18n/ja/docusaurus-plugin-content-docs/current/general-behavior/mmd.md

It's a simple typo fix.
> You can also disable this behavior entirely by attaching the [VRChat Settings](https://modular-avatar.nadena.dev/docs/reference/vrchat-settings) component to your avatar and **disabling the relevant setting.**

fix: typo japanese mmd.md 

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectAnalyzer.LocateReactions.cs
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs
Editor/ReactiveObjects/MeshFiltering/NaNimationFilter.cs
Editor/ReactiveObjects/MeshFiltering/NaNimationInitialStateMunger.cs
Editor/ReactiveObjects/MeshFiltering/NaNimationInitialStateMunger.cs.meta
UnitTests~/ReactiveComponent/ShapeDeletionAnalysis.cs

This change reverts #1660, removing the "infinimation" hack which lead to VRChat crashes, and returns to using NaNimation.
To set initial states of bones, we now use VRCScaleConstraints, which are configured to be active only when animations are disabled, to force the initial bone scale to NaN.
Closes: #1668

fix: VRChat crashes in certain worlds when using Shape Changer Delete modes

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/ReactiveObjects/AnimationGeneration/ReactiveObjectPass.cs
Editor/ReactiveObjects/MeshFiltering/NaNimationFilter.cs
Editor/ReactiveObjects/MeshFiltering/NaNimationInitialStateMunger.cs
Editor/ReactiveObjects/MeshFiltering/NaNimationInitialStateMunger.cs.meta
UnitTests~/ReactiveComponent/ShapeDeletionAnalysis.cs

This change reverts #1660, removing the "infinimation" hack which lead to VRChat crashes, and returns to using NaNimation.
To set initial states of bones, we now use VRCScaleConstraints, which are configured to be active only when animations are disabled, to force the initial bone scale to NaN.
Closes: #1668

[Rebase] fix: VRChat crashes in certain worlds when using Shape Changer Delete modes 

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
CHANGELOG-jp.md
CHANGELOG.md
Editor/FixupPasses/FixupHeadChopRootBone.cs
Editor/FixupPasses/FixupHeadChopRootBone.cs.meta
Editor/PluginDefinition/PluginDefinition.cs

When we perform NaNimations, we disable the "update when offscreen" option on the affected renderer.
This has a side effect: If the root bone is a bone underneath the head, then when the head is scaled down to
a near-zero size, the bounding box of the renderer is also scaled down to a near-zero size, and is then culled
in first-person view.
To avoid this, we now detect when the root bone is the head (or a child of the head) and, in this case, create a
substitute root bone with VRCHeadChop to disable this behavior.

fix: culling issues with rootbone=head

---

Editor/FixupPasses/FixupHeadChopRootBone.cs

AvatarRoot に代替が生成されてしまうため、バウンスが埋まりますね .... 
ひとまず、代替となるボーンの子にする形にしてみました。

fix: Incorrect parent for substitute transform.

---

CHANGELOG-PRERELEASE-jp.md
CHANGELOG-PRERELEASE.md
Editor/FitPreviewWindow/BoneInfo.cs
Editor/FitPreviewWindow/ShadowBoneHierarchy.cs
Editor/FitPreviewWindow/nadena.dev.modular-avatar.fit-preview.asmdef
Editor/FitPreviewWindow/nadena.dev.modular-avatar.fit-preview.asmdef.meta
Editor/assembly-info.cs
Runtime/assembly-info.cs

- PB and collider settings were not updating in realtime
- Build would break without VRCSDK present
- We'll eventually support fit preview without VRCSDK, but not in the initial release.

fix: issues with fit preview
